### ISSUE TITLE
cch Overrides lovelace background image 

### ISSUE THREAD

**Issue by Underknowledge** [maykar/compact-custom-header#100]
## Describe the bug:
Whenever I have a card configured a card with an background and have cch enabled it replaces the background of the card with `paper-card-background-color` - getting loaded first - but then overritten.

## Config YAML:
```yaml
background: center / cover no-repeat url("/local/jpg/bg/2.jpeg") fixed
badges: []
cards:
  - cards:
      - !include 101_bad1.yaml
      - !include 001_settings/custom-header.yaml
      ....
.....
....
```

```yaml
menu: overflow
chevrons: true
options: clock
clock_format: 24
exceptions:
  - conditions:
      user: falcion
    config:
      #voice: show
      header: false

  - conditions:
      user_agent: KFFOWI
    config:
      show_tabs: 1,6,10,2
      
```
enabled cch: 
![image](https://user-images.githubusercontent.com/20793849/55870373-b7de7480-5b88-11e9-98c1-8e88597f2543.png)
Disabled cch:
![image](https://user-images.githubusercontent.com/20793849/55870428-d93f6080-5b88-11e9-89f4-693618216e96.png)

## HA and/or Browser Error:
None

## HA, Card, and Browser Versions:
Home Assistant: 0.91.2, YAML Mode
cch: 1.0.2b9
Chrome Version 73.0.3683.103

**Comment by maykar** [comment]
Sorry, the bot closed this one since you removed the error section of the template.

I am unable to reproduce this one. Do you get any errors in the HA log or in your browsers dev tools (F12)? Do you have the first view setup as "main_config"? Are you using card-modder or anything else to style lovelace and if so could you share that code?

**Comment by Underknowledge** [comment]
Dont worry - Wanted to make it prittey. 
Didnt even thourght on the other cards that they could interfier 🤦‍♂️ 
Its then probably from the `vertical-stack-in-card ` where I placed the cch config in 
____
after friggeling with the config - Its now clear that cch isnt playing nicely with `vertical-stack-in-card ` at all. Removed the `custom:` and `-in-card` and its loading the background. 

was 
```yaml
  - cards:
      - !include 101_bad1.yaml
      - !include 001_settings/custom-header.yaml
      - !include 102_bad2.yaml
    title: ' '
    type: 'custom:vertical-stack-in-card'
```
Now
```yaml
  - type: vertical-stack
    cards:
    - cards:
        - !include 101_bad1.yaml
        - !include 102_bad2.yaml
      title: ' '
      type: 'vertical-stack'
    - !include 001_settings/custom-header.yaml
```
still using custom:layout-card, custom:useful-markdown-card, and custom:card-modder in the included files. Working like a charm
