### ISSUE TITLE
tabContainer is null

### ISSUE THREAD

**Issue by jimmycuadra** [maykar/compact-custom-header#101]
## Describe the bug:
Loading the Home Assistant UI with this card results in the error "tabContainer is null" from compact-custom-header.js:456:9.

## Config YAML:
```yaml
resources:
  - url: "/local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.0.3b0"
    type: "module"
views:
  - title: Example
    cards:
      - type: "custom:compact-custom-header"
```
## HA and/or Browser Error:

"tabContainer is null" : compact-custom-header.js:456:9.

The card does not appear at all.

## HA, Card, and Browser Versions:

Card version: 1.0.3b0
Home Assistant version: 0.91.3
Browser: Firefox 66.0.3 on macOS 10.14.4

I currently have only one view in my UI, which I believe causes the "tab container" to disappear. I'm guessing the logic for this card is assuming it is always there when it might not be. I haven't looked at the code to verify this, but maybe that will help.
