### ISSUE TITLE
Having either a gap under the header or losing some of my iframe

### ISSUE THREAD

**Issue by imbaimbaimba** [maykar/compact-custom-header#102]
## Describe the bug:
When using compact-custom-header on a panel view with an iframe, I can only get it to either have a gap under the header, or alternative eat up the top of the iframe. I tried clearing cache, using incognito mode and various configs.

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
  - title: Dakboard 1
    panel: true
    icon: mdi:view-dashboard
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: !secret dakboard        
          - type: custom:compact-custom-header
            main_config: true


  - title: Dakboard test
    panel: true
    icon: mdi:view-dashboard
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: !secret dakboard     
```
## HA and/or Browser Error:
Couldn't find any errors

## HA, Card, and Browser Versions:
Home Assistant: 0.91.4
Compact-custom-header: 1.0.3b2
YAML mode
Google chrome / MS Edge

[Screenshot of what I see with two different configs](https://i.imgur.com/EOjvlJo.png)

I think I got it all already.

**Comment by maykar** [comment]
When using `panel: true` you have to put it in a vertical stack like your first example, this is why it overlaps in your second example.

The gap you are experiencing looks to be the normal amount of padding between the header and the card. If you disable CCH is the gap less than what you experience with it enabled?

**Comment by imbaimbaimba** [comment]
> When using `panel: true` you have to put it in a vertical stack like your first example, this is why it overlaps in your second example.
> 
> The gap you are experiencing looks to be the normal amount of padding between the header and the card. If you disable CCH is the gap less than what you experience with it enabled?

Thank you for your reply.

If I disable CCH, I get the same as the right-most screenshot from the picture I linked. No gap, but part of the iframe is cut off.

This is actually useful for some iFrames. I for example have one iFrame where I do not want to show the top navigation bar from the page I am embedding, and just leaving out CCH on that view, still gives me the compact header, but cuts the top of the frame.

**Comment by maykar** [comment]
I'm sorry, I misunderstood. The gap is under the current tab indicator. It looks like the header is taller than usual, didn't notice that on first look. That's strange and I can't seem to replicate it. Will do a bit more testing later tonight and get back to you.

**Comment by imbaimbaimba** [comment]
> I'm sorry, I misunderstood. The gap is under the current tab indicator. It looks like the header is taller than usual, didn't notice that on first look. That's strange and I can't seem to replicate it. Will do a bit more testing later tonight and get back to you.

Sounds great. No rush, take your time!

If you need me to test anything, let me know.

**Comment by maykar** [comment]
Can't seem replicate this one. Could you share the site in the iframe? I understand this could be something you want to keep private or it might be self hosted, so if not no worries. Can you try with a different site in the iframe? Does this only happen in the view with this iframe?

**Comment by imbaimbaimba** [comment]
> Can't seem replicate this one. Could you share the site in the iframe? I understand this could be something you want to keep private or it might be self hosted, so if not no worries. Can you try with a different site in the iframe? Does this only happen in the view with this iframe?

Hmm, I just experimented a bit with it.

The iframe I have the gap on is my dakboard ( https://dakboard.com/site ) so I am afraid I cannot share the private URL. I currently have this code for the view:
```yaml
  - title: Dakboard 1
    panel: true
    icon: mdi:view-dashboard
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: !secret dakboard        
          - type: custom:compact-custom-header
            main_config: true
```
It looks like this:
[Picture](https://i.imgur.com/4jujL6K.png)

On the Home Assistant app on my phone, it doesn't even work:
[Picture](https://i.imgur.com/WitVz3z.png)

Same for my wall-mounted android tablet running WallPanel. This is very unfortunate, as this is where it is meant for :( 
[Picture](https://i.imgur.com/M9FkOJu.jpg)

On regular mobile browsers, it has the gap, but works, like on pc:
[Picture](https://i.imgur.com/rcyfIT3.png)

Other webpages render the same results on PC. Example from our local news site:
[Picture](https://i.imgur.com/IzGX0Sl.png)

Code for that:
```yaml
  - title: Test
    panel: true
    icon: mdi:view-dashboard
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: https://www.dr.dk/
          - type: custom:compact-custom-header
```

Not sure what is going on, but would really like to fix the gap and fix to make the iframe work in apps .
