### ISSUE TITLE
cch-background does not apply when set from the theme

### ISSUE THREAD

**Issue by capstan1** [maykar/compact-custom-header#109]
## Describe the bug:

I try to style CCH using the theme. I copied over the configuration outlined in your [styling guide](https://github.com/maykar/compact-custom-header/wiki/Styling-Config). The colors are applied except for the background image. I tried to change to a color (black), but to no avail.
I can set the background color with:
- `primary color` within the lovelace theme (but this also effects other parts of lovelace)
- `background` within the cards settings

`background` overrides the setting of `primary color`, I still tried to disable `primary-color` but `cch-background` still does nothing.
## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
  primary-color: 'rgba(89,87,86,0.8)'        
  text-primary-color: '#FFF'                                                      # Text
  # Compact Custom Header
  cch-background: black
  cch-all-buttons-color: red
  cch-button-color-menu: black
  cch-button-color-notifications: yellow
  cch-button-color-voice: black
  cch-button-color-options: red
  cch-all-tabs-color: red
  cch-tab-indicator-color: yellow
  cch-active-tab-color: blue
  cch-notify-indicator-color: "#00FFFF"
  cch-notify-text-color: brown
```
## HA and/or Browser Error:

none

## HA, Card, and Browser Versions:

CCH-version: 10.0.3b2
Home Assistant version: 0.92.2
Browser: chrome 74.0.3729.131
