### ISSUE TITLE
Menu icon is placed on top of first tab's icon

### ISSUE THREAD

**Issue by capstan1** [maykar/compact-custom-header#112]
## Describe the bug:

Since upgrade to the latest version the menu icon is placed right on top of the first tab.
![image](https://user-images.githubusercontent.com/17147867/57794445-f21cd200-7743-11e9-9da2-00097639f148.png)

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
disable: false
header: true
main_config: true
notifications: overflow
redirect: true
type: 'custom:compact-custom-header'
voice: hide
chevrons: true
```
## HA and/or Browser Error:

Is still functional
## HA, Card, and Browser Versions:

version of this card: 1.0.3b3
HA version: 0.92.2
brwoser: Google Chrome Version 74.0.3729.131, Mobile Chrome is affected, too

**Comment by maykar** [comment]
Any errors in chrome dev tools (F12) or ha logs? Have you done a full refresh, clear cache?

**Comment by brianajensen2** [comment]
Same here :-(

**Comment by maykar** [comment]
@brianajensen2, if you're having the same issue, the same questions apply. Also, try the latest release 1.0.3b5

**Comment by brianajensen2** [comment]
Not working, and have made a full refresh

**Comment by maykar** [comment]
@brianajensen2 Any errors in chrome dev tools (F12) or ha logs? What does your config look like? HA, Card, and Browser Versions?

**Comment by brianajensen2** [comment]
no errors in chrome or HA, Chrome Version 74.0.3729.157 
        cards:    
          - type: custom:compact-custom-header
            main_config: true
            tab_indicator_color: red
            header: true
            menu: show
            options: clock
            background: transparent
            active_tab_color: red
            clock_format: 24
            notifications: false
            redirect: false

**Comment by maykar** [comment]
Thank you, looking into it. You're not alone, few others on the HA forums are having the same issue.

**Comment by ghost** [comment]
Same issue of overlapping icon and no clock with release 1.0.3b5. I did receive and error in chrome and brave. Not sure if it will be any help or not but thought I would post it just in case. No errors in HA

`compact-custom-header.js?track=true:1062 Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at HTMLElement.buildRanges (compact-custom-header.js?track=true:1062)
    at HTMLElement.hideTabs (compact-custom-header.js?track=true:631)
    at HTMLElement.run (compact-custom-header.js?track=true:223)
    at HTMLElement.buildConfig (compact-custom-header.js?track=true:171)
    at HTMLElement.updated (compact-custom-header.js?track=true:74)
    at HTMLElement.performUpdate (app.7bd99ba1.js:2)
    at HTMLElement._enqueueUpdate (app.7bd99ba1.js:2)`

### **HA, Card and Browser Versions :**
HA version : 0.92.2
Custom Header Version : 1.0.3b5
Chrome Version : 74.0.3729.131
Brave Version : 0.64.75 Chromium : 74.0.3729.131

### **Config : **
``` YAML
clock format: '24'
clock_am_pm: false
clock_date: false
clock_format: '24'
disable: false
header: true
main_config: true
notifications: overflow
options: clock
redirect: true
type: 'custom:compact-custom-header'
voice: overflow
menu: overflow
exceptions: []
```
