### ISSUE TITLE
Bell and options icon on top of tab icons.

### ISSUE THREAD

**Issue by Sjeff** [maykar/compact-custom-header#113]
## Describe the bug:
After last update the bell and options icon are on top of the underlying tab icons.
Happens on IOS and chrome.

IOS: 
<img width="152" alt="Image-1" src="https://user-images.githubusercontent.com/11430228/57804520-22239f80-775b-11e9-8f53-f20ad900dd75.png">

chrome: 
![Capture](https://user-images.githubusercontent.com/11430228/57804595-5303d480-775b-11e9-8c5d-4e3fc9dedeb6.JPG)

## Config YAML:
```yaml
type: custom:compact-custom-header
main_config: true
disable: false
header: true
menu: show
notifications: show
voice: hide
options: show
chevrons: false
clock_format: 24
clock_am_pm: false
clock_date: false
hide_tabs: "9,11"
redirect: true
default_tab: "0"
# background: 
notify_indicator_color: red
```
## HA and/or Browser Error:
No errors show in HA Log or Dev-Tools

## HA, Card, and Browser Versions:
HA 0.92.2  (Yaml mode)
CCH 1.0.3b5
Chrome 74.0.3729.157
