### ISSUE TITLE
Graphical Bug in latest update

### ISSUE THREAD

**Issue by SeLLeRoNe** [maykar/compact-custom-header#114]
## Describe the bug:
The left button for "home" and to externd the later menu are overlapping

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
---
type: 'custom:compact-custom-header'
main_config: true
disable: false
header: true
background_image: true
menu: show
notifications: show
voice: show
options: clock
clock_format: 24
clock_am_pm: false
hide_tabs:
exceptions:
  - conditions:
      user: sonia
    config:
      hide_tabs: 5,6,7,8,9,10
  - conditions:
      user_agent: mobile
#      media_query: (max-width: 600px)
    config:
      hide_tabs: 5,6,7,8,9,10

```
## HA and/or Browser Error:

No error in the browser console, few in ha logs but not really related:
2019-05-16 13:01:39 ERROR (MainThread) [custom_components.custom_updater] Tried to serve up '/home/ha/.homeassistant/www/lovelace/cards/calendar-card.js.map' but it does not exist
2019-05-16 13:01:39 ERROR (MainThread) [custom_components.custom_updater] Tried to serve up '/home/ha/.homeassistant/www/lovelace/cards/light-entity-card.js.map' but it does not exist
2019-05-16 13:02:19 ERROR (MainThread) [custom_components.custom_updater] Tried to serve up '/home/ha/.homeassistant/www/lovelace/cards/light-entity-card.js.map' but it does not exist
2019-05-16 13:02:19 ERROR (MainThread) [custom_components.custom_updater] Tried to serve up '/home/ha/.homeassistant/www/lovelace/cards/calendar-card.js.map' but it does not exist

## HA, Card, and Browser Versions:

HA 0.93.0
Chrome 74.0.3729.157
Card: 1.0.3b6

![image](https://user-images.githubusercontent.com/9599441/57849285-34ddb900-77db-11e9-93de-81be2f2c531f.png)

Was working before updating the card itself with same Chrome version and HA version
