### ISSUE TITLE
Menu icon is placed on top of first tab's icon

### ISSUE THREAD

**Issue by vitinhosessa** [maykar/compact-custom-header#117]
## Describe the bug:
Same bug as #112 

## Config YAML:
```yaml
clock_am_pm: false
clock_date: true
clock_format: '24'
exceptions: []
main_config: true
type: 'custom:compact-custom-header'
disable: false
header: true
voice: clock
notifications: overflow
chevrons: false
```

## HA, Card, and Browser Versions:
Hassio: 0.93.0
compact-custom-header: 1.0.4
