### ISSUE TITLE
Menu icon is placed on top of first tab's icon

### ISSUE THREAD

**Issue by vitinhosessa** [maykar/compact-custom-header#118]
## Describe the bug:
Same as #112 and the clock is not working too

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
clock_am_pm: false
clock_date: true
clock_format: '24'
exceptions: []
main_config: true
type: 'custom:compact-custom-header'
disable: false
header: true
voice: clock
notifications: overflow
chevrons: false

```
## HA and/or Browser Error:

Still functional, but i cant click the icon that is overlaped.

## HA, Card, and Browser Versions:

Hassio: 0.93.0
compact-custom-header: 1.0.4
Chrome/74.0.3729.131
