### ISSUE TITLE
background-size not reflected in backgroud

### ISSUE THREAD

**Issue by DarrenRatcliffe** [maykar/compact-custom-header#127]
## Describe the bug:
when including the background-size CSS element 'auto' background fails to show image, remove 'auto' element and image shows fine, position is fine etc

## Config YAML:
```yaml
views:
  - badges: []
    cards:
      - background: auto right no-repeat url('/local/pics/pbi-new.png')
        main_config: true
        notifications: overflow
        type: 'custom:compact-custom-header'
        voice: overflow

```
## HA, Card, and Browser Versions:

1.0.4b9 < CCH
0.93.1 < HA
74.0.3729.169 < Chrome

**Comment by maykar** [comment]
Need to follow the [CSS Syntax  for the background property](https://www.w3schools.com/cssref/css3_pr_background.asp):

`background: bg-color bg-image position/bg-size bg-repeat bg-origin bg-clip bg-attachment initial|inherit;`

```yaml
views:
  - badges: []
    cards:
      - background: right/auto no-repeat url('/local/pics/pbi-new.png')
        main_config: true
        notifications: overflow
        type: 'custom:compact-custom-header'
        voice: overflow
```
