### ISSUE TITLE
Tab Borders

### ISSUE THREAD

**Issue by apop880** [maykar/compact-custom-header#128]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to add borders to tab icons. I have views I'd like to group together by putting a border at the left and right sides of the tab groups.

**Additional Context**
It looks like the `paper-tab` would be the place to be able to apply a border-left or border-right conditionally.

**Comment by maykar** [comment]
Rather than adding this on it's own, I think it would make more sense to open it up to any css property. Something like:
```yaml
cch:
  button_css:
    menu: "box-shadow: 5px 10px #888888;"
  tab_css:
    0: "border-left: 2px solid red;"
```
