### ISSUE TITLE
Options Menu Doesn’t Work in iOS Safari

### ISSUE THREAD

**Issue by chipriley** [maykar/compact-custom-header#129]
## Describe the bug:
When attempting to use the Options menu on iOS Safari, none of the options are tappable.  The menu displays but you can’t select an option.  This happens regardless of whether it’s a clock menu or a regular Options menu. Has been happening on iOS 12 and 13 (Beta) and has been happening at least since HA 0.93.2 but possibly throughout 0.93.  Currently on 0.94.2.

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
- type: custom:compact-custom-header
        main_config: true
        menu: overflow
        background: true
        options: clock
        voice: hide
        clock_format: 12
        clock_am_pm: true
        clock_date: true
```
## HA and/or Browser Error:

None in HA. 
## HA, Card, and Browser Versions:

Card Version: 1.0.4b9
HA Version: 0.94.2
Browser: iOS Safari (iOS 12 and 13)
YAML Mode

This has happened in the past but was working for a while until recently (last couple of weeks).  Actually, this may not be a CCH problem as disabling with ?disable_cch doesn’t fix the Options menu.  Perhaps there’s a conflict with another card.  I’ll try hooking up to my Mac and pulling logs.  Works fine on a desktop.
