### ISSUE TITLE
problem with default_tab and redirect

### ISSUE THREAD

**Issue by Gandohr** [maykar/compact-custom-header#139]
## Describe the bug:
default_tab is not working, neither is the redirect option.
when going to the overview page http://<ip>:<port> or http://<ip>:<port>/lovelace
it will always go to /0, even if 0 is hidden, and default is set to 1

when hidding pages 3,4 they are hidden in the view, they are skipped while swiping
but will be shown when typing in the url http://<ip>:<port>/lovelace/3

In Chrome 75.0.3770.90
      when going to http://<ip>:<port> it does go to the default_tab
      when going to http://<ip>:<port>/lovelace it goes to /1
      when clicking on overview it goes to /lovelace and then will end up at /0

## Config YAML:
```yaml
cch:
  default_tab: '1'
  options: clock
  clock_format: 24
  hide_tabs: '0'
  swipe: true
  swipe_amount: 10
  swipe_animate: none
  swipe_skip: ''
  swipe_wrap: true
  swipe_prevent_default: false
  exceptions:
    - conditions:
        user: <username>
      config:
        default_tab: '4'
    - conditions:
        user: <username>
        user_agent: Mobile
        #media_query: (max-width: 600px) (if enabled it gives an error)
      config:
        hide_tabs: '0,4,5'
        redirect: true
        kiosk_mode: false
        default_tab: 1

```
## HA and/or Browser Error:
No error in there

## HA, Card, and Browser Versions:
Home Assistant: 0.95.0
Browser Safari 12.1.1 (fail)
Browser Safari for iPad and iPhone (fail)
Browser Chrome 75.0.3770.90 (partition fail)
      when going to http://<ip>:<port> it does go to the default_tab
      when going to http://<ip>:<port>/lovelace it goes to /1
      when clicking on overview it goes to /lovelace and then will end up at /0
