### ISSUE TITLE
Does not work with Chrome for Android

### ISSUE THREAD

**Issue by SomeoneCares** [maykar/compact-custom-header#140]
## Describe the bug:
Does not work with Chrome for Android, when i select Configure UI from android device there is not CCH Settings although when i select Raw Config Editor i still see the entries

## Config YAML:
```yaml
resources:
  - type: module
    url: /local/mini-media-player-bundle.js?v=1.0.2
  - type: module
    url: /local/slider-entity-row.js
  - type: module
    url: /local/compact-custom-header/compact-custom-header.js?v=0.0.1
  - type: js
    url: /customcards/github/thomasloven/card-tools.js?track=true
  - type: js
    url: /customcards/github/thomasloven/layout-card.js?track=true
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
  - type: module
    url: /customcards/github/custom-cards/tracker-card.js?track=true
  - type: js
    url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
  - type: js
    url: /local/monster-card.js
cch:
  swipe: true
  swipe_amount: '10'
  voice: hide
title: Home
views:
  - badges: []
    cards:
      - entities:
```
## HA and/or Browser Error:
No errors

## HA, Card, and Browser Versions:
HA version 0.95.1
CCH version 1.16
Browser user agent
Mozilla/5.0 (Linux; Android 9; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
