### ISSUE TITLE
CCH Settings panel is blank in Chrome

### ISSUE THREAD

**Issue by helenclarko** [maykar/compact-custom-header#142]
## Describe the bug:

CCH Settings panel is blank/doesn't load

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
cch:
  chevrons: false
  clock_date: false
  clock_format: '12'
  exceptions:
    - conditions:
        user: Tablet
      config:
        disable: false
        menu: hide
    - conditions: {}
      config: {}
  main_config: true
  notifications: hide
  options: clock
  sidebar_closed: false
  swipe: 'true'
  swipe_animate: swipe
```
## HA and/or Browser Error:

```
Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at styleButtons (compact-custom-header.js:414)
    at run (compact-custom-header.js:105)
    at compact-custom-header.js:90
```
## HA, Card, and Browser Versions:

CCH version: 1.1.6
HA Version: 0.95.1
Browser Type: Chrome 75.0.3770.100

![image](https://user-images.githubusercontent.com/2774385/60358067-42be5680-99a3-11e9-8fb8-bc93d2d1e6c1.png)

**Comment by vstoms** [comment]
Same in Firefox and Microsoft Edge Dev

**Comment by maykar** [comment]
@helenclarko This may not solve your problem, but will prevent others. This removes config that isn's needed and ones that could cause errors. Update your config to:
```yaml
cch:
  chevrons: false
  clock_format: 12
  exceptions:
    - conditions:
        user: Tablet
      config:
        menu: hide
  notifications: hide
  options: clock
  swipe: true
  swipe_animate: swipe
```

@vstoms Do you get the exact error message and what does your config look like?
