### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by brettlg** [maykar/compact-custom-header#148]
## Describe the bug:

Current version of CCH not honouring **background: 'rgba(0, 0, 0, 0.2)'**
Old version was perfect, config was just moved from card to CCH:
## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
cch:
  - type: 'custom:compact-custom-header'
    main_config: true
    background: 'rgba(0, 0, 0, 0.2)'
    menu: show
    options: show
    voice: show
    notifications: clock
    clock_format: '12'
    clock_date: true
    date_locale: en-gb
    disable: false
    chevrons: true
```
## HA and/or Browser Error:

Card is still functional just visual styling not correct
## HA, Card, and Browser Versions:

Safari on OS 10.14 and Chrome on OS 10.14

Homeassistant V 0.95.4 
CCH V 1.1.8

**Comment by maykar** [comment]
Remove `type: 'custom:compact-custom-header'` and `main_config: true`
```yaml
cch:
    background: 'rgba(0, 0, 0, 0.2)'
    menu: show
    options: show
    voice: show
    notifications: clock
    clock_format: '12'
    clock_date: true
    date_locale: en-gb
    disable: false
    chevrons: true
```
