### ISSUE TITLE
CCH Editor shows only empy box

### ISSUE THREAD

**Issue by papperone** [maykar/compact-custom-header#150]
## Describe the bug:
Since 1.1.4 upgrade of this component I could not see the config panel; I went up to 1.1.9 (latest) and behaviour is basically the same; the below YAML I added manually as the component only add a "cch: null" line

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
cch:
  clock_date: true
  clock_format: 24

```
## HA and/or Browser Error:

![immagine](https://user-images.githubusercontent.com/28104633/60397466-efd4d280-9b4d-11e9-9b01-00d7bf1974d3.png)
Card features are working only if I manullay set in the Raw Config Mode, but the config panel is not showing

## HA, Card, and Browser Versions:

Hassio: 0.95.4
Compat Custom Header: 1.1.9
Browsers testes: Chrome; Firefox, Opera, Explorere and Edge
YAML mode: no, I use inline configuration of Yaml

![immagine](https://user-images.githubusercontent.com/28104633/60397446-aab0a080-9b4d-11e9-978e-bf0ddd0cdd15.png)
