### ISSUE TITLE
Hass.io v 0.96.0b0 ShadowRoot Failure

### ISSUE THREAD

**Issue by michaeldvinci** [maykar/compact-custom-header#160]
## Describe the bug:

CCH wont load in new beta.

## Config YAML:
```yaml

cch:
  clock_date: true
  clock_format: 12
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        hide_tabs: '0'
        menu: hide
        options: hide
    - conditions:
        user_agent: OS X
      config:
        hide_tabs: '1,2'
    - conditions:
        user_agent: Windows
      config:
        hide_tabs: '1,2'
  menu: show
  notifications: clock
  options: show
  swipe: true
  type: 'custom:compact-custom-header'
  voice: show

```
## HA and/or Browser Error:
customcards/github/maykar/compact-custom-header.js?track=true:210:46 TypeError: null is not an object (evaluating 'root.querySelector("hui-notification-drawer").shadowRoot')
customcards/github/maykar/compact-custom-header.js?track=true:211:5 Uncaught TypeError: Cannot read property 'shadowRoot' of null

## HA, Card, and Browser Versions:

cch version: 1.2.1
hassio version: 0.96.0b0

![image](https://user-images.githubusercontent.com/8780953/61074537-f2ed7f80-a3e5-11e9-8a7c-3687c43d199c.png)
