### ISSUE TITLE
Conditional Styling Templates not hiding tabs and buttons

### ISSUE THREAD

**Issue by wiuwiu** [maykar/compact-custom-header#163]
## Describe the bug:
Conditional Styling Templates not hiding tabs and buttons. 

## Config YAML:
```yaml
cch:
  default_tab: 1
  hide_help: true
  menu: overflow
  notifications: show
  voice: show
  options: clock
  clock_format: 24
  clock_date: true
  exceptions:
    # user Adam
    - conditions:
        user: Adam
      config:
        default_tab: 11
        kiosk_mode: true
        show_tabs: 11,12,13
        menu: hide
        notifications: clock
        options: hide
        swipe: true
    # user Eva
    - conditions:
        user: Eva
      config:
        default_tab: 11
        kiosk_mode: true
        show_tabs: 11
        menu: hide
        notifications: clock
        options: hide
        swipe: true
  conditional_styles:
    template:

      # hide notifications
      - button:
          notifications:
            display: >
              if (notifications) 'show';
              else 'hide';

      # hide tab 1
      - tab:
          1:
            display: >
              if (states['alarm_control_panel.alarm'].state == 'armed_away') 'hide';
              else if (states['alarm_control_panel.alarm'].state == 'armed_home') 'hide';
              else 'show';
      
      # hide tab 2
      - tab:
          2:
            display: >
              if (states['alarm_control_panel.alarm'].state == 'armed_away') 'hide';
              else if (states['alarm_control_panel.alarm'].state == 'armed_home') 'hide';
              else 'show';

```
## HA and/or Browser Error:
None.

## HA, Card, and Browser Versions:
HA: 0.95.4
CCH: 1.2.2
Browser: Firefox 68.0
Configuration: YAML

Changing icons or colors works perfectly.
