### ISSUE TITLE
Double Menu icons

### ISSUE THREAD

**Issue by acordill** [maykar/compact-custom-header#165]
## Describe the issue:

On beta of HA (0.96.0b1) there are two menu buttons, one in side bar and one on view.  There should only be one.

## Config YAML:

```yaml
cch:
  active_tab_color: blue
  clock_date: true
  clock_format: '24'
  date_locale: en-US
  default_tab: '2'
  exceptions:
    - conditions:
        user: Andy
        user_agent: Linux x86_64
      config:
        clock_format: '24'
        default_tab: '2'
        hide_tabs: []
        menu: show
        notifications: show
        options: clock
        show_tabs: 2 to 12
        voice: overflow
    - conditions:
        user: Andy
        user_agent: Pixel 2 XL
      config:
        clock_format: '24'
        default_tab: '1'
        hide_tabs: []
        menu: show
        notifications: overflow
        options: clock
        show_tabs: '1,3 to 10,12'
        voice: overflow
    - conditions:
        user: Kiosk
      config:
        clock_format: '24'
        date_locale: en-US
        default_tab: '2'
        hide_tabs: []
        kiosk_mode: true
        menu: show
        notifications: overflow
        options: clock
        show_tabs: '2'
        sidebar_swipe: false
        voice: clock
    - conditions:
        user: Renee
      config:
        clock_format: '24'
        date_locale: en-US
        default_tab: '2'
        hide_tabs: []
        menu: show
        notifications: overflow
        options: clock
        show_tabs: '0 to 9,11,13'
        voice: overflow
  hide_help: true
  options: clock
  redirect: false
  show_tabs: 0 to 13
  sidebar_closed: true
  swipe: true
  swipe_prevent_default: true
  voice: overflow
  menu: overflow
```
## HA and/or Browser Error:

No error messages that I am aware of
## Versions and Browser:

CCH = 1.2.6
HA = 0.96.0b1
Browser = Chrome
