### ISSUE TITLE
Background doesnt fill when hiding header

### ISSUE THREAD

**Issue by isabellaalstrom** [maykar/compact-custom-header#169]
## Describe the issue:

When hiding header/using kiosk mode together with a background for the view, the background doesn't fill the screen all the way down. I have tried to look for an option that could fix this, but didnt find any.

## Config YAML:

```yaml
cch:
  disable: false
  header: true
  menu: show
  sidebar_swipe: true
  notifications: show
  voice: hide
  options: clock
  clock_format: 24
  clock_date: true
  date_locale: sv-SE
  swipe: true
  exceptions:
    - conditions:
        user: dashboard
      config:
        show_tabs: 8
        kiosk_mode: true
```
## HA and/or Browser Error:

-

## Versions and Browser:

HA 0.95.4
CCH 1.2.8
Chrome 75.0.3770.100
Yaml mode

![image](https://user-images.githubusercontent.com/22006797/61275773-f2226800-a7ae-11e9-89fe-16e6bcbec43a.png)
