### ISSUE TITLE
[Feature Request] Time and Date CSS

### ISSUE THREAD

**Issue by lordgoata** [maykar/compact-custom-header#170]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Would it/is it possible to edit the font used for the date (and/or time for completeness)? I'd like to show the date under the time in a much smaller font if possible?

**Comment by maykar** [comment]
This could be solved with the proposed solution described in another feature request:
https://github.com/maykar/compact-custom-header/issues/128#issuecomment-518737841

Will update you when something like this is implemented.

**Comment by maykar** [comment]
The ability to change font and size has been added in the latest pre-release 1.3.6

Example and more info here: https://community.home-assistant.io/t/compact-custom-header/83716/1109

**Comment by maykar** [comment]
It is still not possible to have separate sizes/fonts for date and time. I'm not sure if this is something I'd add, but I am still thinking on expanded features of time and date.

**Comment by zibous** [comment]
Yes. please. I try to set the font-size for:
```
# Custom Header settings
cch:
  chevrons: true
  clock_date: true
  clock_format: '24'
  options: clock
  button_css:
    options: 'font-size: 9pt;font-weight:300'
  swipe: true
  swipe_wrap: false
  default_tab: 0
  notifications: show
  swipe_prevent_default: true
  exceptions:
    - conditions:
        user: peter.siebler
      config:
        menu: hide
        options: hide
        sidebar_closed: true
        voice: clock
```

![Bildschirmfoto 2019-08-26 um 14 35 54](https://user-images.githubusercontent.com/30198737/63691211-e47ceb00-c80e-11e9-9586-e25ffbdd59ae.png)

But without success. The font size does not change. Change of font works.

**Comment by maykar** [comment]
It appears that when using a date that font size is overwritten. Going to open this one back up and possibly add `date_css` and `time_css` to config options.

**Comment by zibous** [comment]
@maykar 
I tried, but no change. Am I doing something wrong ?

```
# Custom Header settings
cch:
  chevrons: true
  clock_date: true
  clock_format: '24'
  options: clock
  swipe: true
  swipe_wrap: false
  default_tab: 0
  notifications: show
  swipe_prevent_default: true
  button_css:
    options: 'font-size: 9pt;font-weight:300'
  date_css:
    options: 'font-size: 9pt;font-weight:300' 
  time_css:
    options: 'font-size: 9pt;font-weight:300'    
  exceptions:
    - conditions:
        user: peter.siebler
      config:
        menu: hide
        options: hide
        sidebar_closed: true
        voice: clock
```
