### ISSUE TITLE
Missing notification dot icon in mobile mode

### ISSUE THREAD

**Issue by SeanPM5** [maykar/compact-custom-header#174]
## Describe the issue:

With the recent redesigns in HA 0.96 the only way to see if you have notifications without opening the sidebar (on a **mobile device**) is the orange dot that displays over the hamburger icon. 

But this does not seem to work on CCH (unless I missed something). I see it for a split second while refreshing and HA's menu loads but once it gets replaced with the CCH version of the menubar, that orange icon goes away. Would be nice if that could be added.

Here's a comparison of what I mean (HA left, CCH right):

![IMG_1371](https://user-images.githubusercontent.com/9065557/61603443-8eaf9480-ac0b-11e9-83ca-eb7fd6c6814a.PNG)

## Config YAML:

```yaml
cch:
  hide_tabs: '3,4'
  voice: hide
  menu: show
  chevrons: false

  swipe: true
  swipe_animate: none
```
## Versions and Browser:

HA 0.96.3
CCH 1.3.1
Official HA iOS 2.0 app
YAML mode
