### ISSUE TITLE
Missing notification dot icon in mobile mode

### ISSUE THREAD

**Issue by SeanPM5** [maykar/compact-custom-header#175]
## Describe the issue:

With the recent redesigns in HA 0.96 the only way to see if you have notifications without opening the sidebar (on a **mobile device**) is the orange dot that displays over the hamburger icon. 

But this does not seem to work on CCH (unless I missed something). I see it for a split second while refreshing and HA's menu loads but once it gets replaced with the CCH version of the menubar, that orange icon goes away. Would be nice if that could be added.

Here's a comparison of what I mean (HA left, CCH right):

![IMG_1371](https://user-images.githubusercontent.com/9065557/61603443-8eaf9480-ac0b-11e9-83ca-eb7fd6c6814a.PNG)

## Config YAML:

```yaml
cch:
  hide_tabs: '3,4'
  voice: hide
  menu: show
  chevrons: false

  swipe: true
  swipe_animate: none
```
## HA and/or Browser Error:

No errors

## Versions and Browser:

HA 0.96.3
CCH 1.3.1
Official HA iOS 2.0 app
YAML mode

N/A

**Comment by bagobones** [comment]
Just commenting to follow.

**Comment by maykar** [comment]
Fixed in 1.3.2

**Comment by SeanPM5** [comment]
Thanks for fixing it. However I think there’s one tiny issue. Just updated to CCH 1.3.2 and it shows like this on the iOS 2.0b app (not home at the moment to test on desktop):

![alt text](https://i.imgur.com/OUb6JHs.jpg)

You can see the outline/border of the circle in the top right of the hamburger menu, but the dot seems empty and not filled in with the accent-color.

**Comment by maykar** [comment]
Looks like this one is going to be a bit more of a pain than I realized. Not only does it seem that the HA renders the notification dot differently on mobile than it does on PC, but differently on iOS vs android.

**Comment by maykar** [comment]
Just pushed a quick update 1.3.3 to address. Let me know if it helps.

**Comment by SeanPM5** [comment]
Yep it's working perfectly now on iOS (both the stable 1.5.1 and 2.0 beta). Many thanks!

**Comment by bagobones** [comment]
Working on iOS for me now. 1.3.3

On desktop I have "Always hide the sidebar" set in hass, would it be possible to display the dot for desktop in this case as well?

**Comment by maykar** [comment]
That looks to be a bug/feature request for Home Assistant itself and should be reported/handled there, but you could make an indicator using CCH. Something like this:

```yaml
cch:
  conditional_styles:
    - entity: notifications
      condition:
        state: true      # When there are notifications...
      button:             # color menu button yellow.
        menu:
          color: yellow
```

You could even change the icon to a bell or something similar, more here:

https://maykar.github.io/compact-custom-header/Conditional-Styling-Config/
