### ISSUE TITLE
templated icon for tab isnt working anymore after HA update to 96.3

### ISSUE THREAD

**Issue by Mariusthvdb** [maykar/compact-custom-header#177]
## Describe the issue:

templated icon for tab 12 isn't working anymore after updating HA to 96.3

## Config YAML:

```yaml
# https://maykar.github.io/compact-custom-header/Main-Config-Options/
#type: custom:compact-custom-header
#main_config: true
header: true
menu: show
options: show
swipe: true
swipe_animate: none
chevrons: true
#background: transparent
exceptions:
  - conditions:
      user_agent: iPhone
    config:
      menu: hide
      notifications: hide
      header: true
      options: hide
conditional_styles:
  - template:
      tab:
        12:
          - icon: >
              if (entity['sensor.family_home'].state == '0') 'mdi:account-off';
              else if (entity['sensor.family_home'].state == '1') 'mdi:account';
              else if (entity['sensor.family_home'].state == '2') 'mdi:account-multiple';
              else if (entity['sensor.family_home'].state == '3') 'mdi:account-multiple-check';
              else 'mdi:account-group';
  - entity: notifications
    condition:
      state: false      # When there are no notifications...
    button:             # hide notifications button.
      notifications:
        hide: true
```
## HA and/or Browser Error:

2019-07-22 13:30:39 ERROR (MainThread) [frontend.js.latest.201907210] :0:0 Script error.
2019-07-22 13:30:39 ERROR (MainThread) [frontend.js.latest.201907210] :0:0 Script error.
2019-07-22 13:30:51 ERROR (MainThread) [frontend.js.latest.201907210] https://redacted:8123/local/lovelace/resources/compact-custom-header/compact-custom-header.js?v=1.2.0:210:46 TypeError: null is not an object (evaluating 'root
    .querySelector("hui-notification-drawer")
    .shadowRoot')
2019-07-22 13:31:46 ERROR (MainThread) [frontend.js.latest.201907210] https://redacted:8123/local/lovelace/resources/compact-custom-header/compact-custom-header.js?v=1.2.0:210:46 TypeError: null is not an object (evaluating 'root
    .querySelector("hui-notification-drawer")
    .shadowRoot')

## Versions and Browser:

CCH 1.2.3..(not sure though, since the docs mention 1.1.1 to be the latest.. Ive downloaded the version from https://github.com/maykar/compact-custom-header/blob/master/compact-custom-header.js)
browser Safari, Chrome, Mac, desktop and mobile
please see community post: https://community.home-assistant.io/t/compact-custom-header/83716/985?u=mariusthvdb
