### ISSUE TITLE
CCH for older devices & unsupported browsers.

### ISSUE THREAD

**Issue by maykar** [maykar/compact-custom-header#185]
I maintain a version of CCH for older or unsupported devices/browsers here:
https://gist.github.com/maykar/278cf3d81e99a7594d4a0d1677fe981f

Either download or copy from the raw file and add to your resources, be sure to use `type: js` and add to the version number at the end of the URL when updating:

```yaml
resources:
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: js
```
