### ISSUE TITLE
CCH 1.35 issues

### ISSUE THREAD

**Issue by mmatesic01** [maykar/compact-custom-header#186]
## Describe the issue:
Version 1.3.1 works without problems. Upgrading to 1.3.3 or latest 1.3.5, does not hide tabs anymore and slide/flip functions does not work (android 8,0 and 9,0). Reinstalling back 1.3.1 everything is back in order.

## Config YAML:

```yaml
cch:
  default_tab: '0'
  exceptions:
    - conditions:
        user: user
      config:
        default_tab: '1'
        hide_tabs: '0,4,5,6'
        kiosk_mode: true
        menu: show
        notifications: show
        options: show
        swipe: true
        swipe_animate: flip
        voice: hide
  hide_help: true
  hide_tabs: '1'
  swipe: true
  swipe_animate: flip
  voice: hide

```
## HA and/or Browser Error:
No error logs in HA

## Versions and Browser:
CCH 1.3.5, HA 0,97, Browser Samsung browser on android

**Comment by maykar** [comment]
Try removing `notifications: show`. This option is no longer used when using HA versions higher than 0.95 and, though it is ignored on PC, it seems to cause an error on mobile devices.

```yaml
cch:
  default_tab: '0'
  exceptions:
    - conditions:
        user: user
      config:
        default_tab: '1'
        hide_tabs: '0,4,5,6'
        kiosk_mode: true
        menu: show
        options: show
        swipe: true
        swipe_animate: flip
        voice: hide
  hide_help: true
  hide_tabs: '1'
  swipe: true
  swipe_animate: flip
  voice: hide
```
