### ISSUE TITLE
Tabs Area (paper-tabs) width is to small

### ISSUE THREAD

**Issue by zibous** [maykar/compact-custom-header#187]
## Describe the issue:
Tabs Area (paper-tabs) width is to small

![Bildschirmfoto 2019-08-16 um 13 48 52](https://user-images.githubusercontent.com/30198737/63166084-a244f400-c02d-11e9-950a-c7c17c0bbbb6.png)

```
element.style {
    margin-right: 220px;
    margin-left: 60px;
}
```

## Config YAML:

```yaml
# Custom Header settings
cch:
  chevrons: true
  clock_date: true
  clock_format: '24'
  options: clock
  swipe: true
  swipe_wrap: false
  voice: clock
  default_tab: 0
  notify_indicator_color: "#e80000"
  swipe_prevent_default: true
```
## HA and/or Browser Error:
All Browsers (Safari, Chrome, Firefox...)

## Versions and Browser:
```
Home Assistant 0.97.2
arch   armv7l
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
timezone | Europe/Vaduz
version | 0.97.2
virtualenv | true

CARD-TOOLS IS INSTALLED
DeviceID: 3c0a77cc-c3e5b875
compact-custom-header.js: 
COMPACT-CUSTOM-HEADER      Version 1.3.5     
```
How can i fix this ?

**Comment by maykar** [comment]
Seems you have both the voice button and options button set to clock so it is making room for each. Try removing one like the voice clock as it doesn't look like you're using it.
```
cch:
  chevrons: true
  clock_date: true
  clock_format: '24'
  options: clock
  swipe: true
  swipe_wrap: false
  default_tab: 0
  notify_indicator_color: "#e80000"
  swipe_prevent_default: true
```
