### ISSUE TITLE
Firefox 60 and Edge Support

### ISSUE THREAD

**Issue by jgalak** [maykar/compact-custom-header#192]
## Describe the issue:

I just installed CCH for the first time using HACS.  Once I added the relevant code using the Lovelace Raw config editor, the following occurred:

In Firefox (60.8.0esr 64bit), going to lovelace at all causes the browser tab to freeze, and stay frozen until Firefox displays "A web page is slowing down your browser... Stop It/Wait".  No amount of waiting makes it better (10+ minutes).  I was only able to get Lovelace back by manually editing the lovelace json file to remove the CCH references and restarting HA.

In Edge, it doesn't freeze, but every lovelace tab is blank.  The header is there, the backgrounds of the tabs that have backgrounds set are there, but all cards are missing.  I **can** enter the editor in Edge (hadn't realized this before resorting to the manual edit above).

## Config YAML:

```yaml
background: center / cover no-repeat url("/background.png") fixed
excluded_entities:
  - weblink.router
resources:

  - type: js
    url: /local/group-card.js
  - type: js
    url: /local/card-tools.js?track=true
  - type: js
    url: /local/popup-card.js?track=true
  - type: module
    url: /local/roku-card.js?v=0
  - type: js
    url: /local/auto-entities.js
  - type: js
    url: /local/fold-entity-row.js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
cch:
  options: clock
title: Clarendon Abbey
views:
  - cards:
      - entities:
          - entity: sensor.jg
          - entity: sensor.lkw
          - entity: binary_sensor.occupied
        show_state: true
.
.
.
```
Everything after that is my previously working Lovelace.  I'd not done anything with CCH except add the resource and the `cch` entry.

## HA and/or Browser Error:

From firefox dev-tools:

```
JQMIGRATE: jQuery.browser is deprecated
jquery-migrate-1.0.0.js:29:4
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
community
TypeError: this.toggleAttribute is not a function[Learn More]
ha-user-badge.ts:43:4
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!
info
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
CARD-TOOLS IS INSTALLED
DeviceID: 12e92e65-cda57e37
card-tools.js:403:1
 COMPACT-CUSTOM-HEADER 
     Version 1.3.6     
compact-custom-header.js:2689:1
Error: Script terminated by timeout at:
tabContainerMargin@https://gerfalcon.duckdns.org:8123/community_plugin/compact-custom-header/compact-custom-header.js:280:3
styleButtons/<@https://gerfalcon.duckdns.org:8123/community_plugin/compact-custom-header/compact-custom-header.js:642:7
```

## Versions and Browser:

CCH: I started with 1.3.5, but also tried 1.3.6 bets
HA: Hass.io 0.97.2
Browser: Firefox 60.8.0esr 64bit and Edge 42.17134.1.0, both on Win10 64
Storage mode I guess?  The one where you use the UI-based browser.

ETA:  Using Edge to remove the CCH code in the Raw config editor, just like editing the json on disk, didn't fix the problem immediately - just reloading the page, including a shift-reload, didn't make it work in either browser.  It took a restart of HA to fix the problem in Firefox.

Note that the Edge problem has persisted, so it may not have anything to do with CCH - I've never used Edge to go to Lovelace before.
