### ISSUE TITLE
Swipe groups not working at all

### ISSUE THREAD

**Issue by jimz011** [maykar/compact-custom-header#195]
## Describe the issue:
When setting `swipe_groups` the swipe feature will stop working. No tabs can be swiped on.
When commenting this line out it works again. I have tried single groups, multiple groups. Single and double quotes. Refresh, Clearing Cache. Nothing changed.

## Config YAML:
```yaml
menu: hide
options: hide
notifications: hide
voice: hide
header: false
chevrons: false
notify_indicator_color: "#e80000"
swipe: true
swipe_wrap: false
background: 'rgba(0,0,0,0.3)'
hide_tabs: '5 to 30'
default_tab: 1
swipe_groups: '0 to 4'
```
## HA and/or Browser Error:
No Errors shown

## Versions and Browser:
CCH Version: 1.3.6
HA Version: 0.98.4
Browser: HA app on iOS (so probably safari)

**Comment by maykar** [comment]
Can you try adding `swipe_skip_hidden: false`? I think this is may be due to the fact that you're hiding the entire header, so all tabs are seen as hidden and it's skipping all of them.

**Comment by skynet01** [comment]
i can confirm i have the same behavior on 1.3.8. Groups are set up as an exception on an iPad. Also on iPad if you set hide the header sometimes it doesn't hide and big top area is empty. Rolled back to 1.3.5
```
cch:
  exceptions:
    - conditions:
        user_agent: iPad
      config:
        compact_header: false
        default_tab: []
        header: false
        hide_tabs: []
        menu: show
        notifications: show
        options: show
        show_tabs: []
        swipe: true
        swipe_amount: '20'
        swipe_animate: swipe
        swipe_prevent_default: true
        swipe_skip: '3'
        voice: show
  hide_help: true
  hide_tabs: '4'
  options: clock
  voice: clock
```

**Comment by maykar** [comment]
Just released 1.3.9 to address these issues as well as attempt to fix some of the iOS strangeness surrounding the "swipe" animation (got an iPad for testing!). Be sure to clear cache/ refresh. I added the version number to the CCH settings window so you can check that you are using the latest and not a cached version on mobile devices. Let me know if it helps.

**Comment by skynet01** [comment]
I can confirm that swiping now works with 1.4.0. However i still have a big space at the top that shows up. This is on iPad Air2
![IMG_246A4BDFBDDE-1](https://user-images.githubusercontent.com/8117544/65658903-6e6ece00-dfde-11e9-9077-2eb251bba578.jpeg)

**Comment by maykar** [comment]
@skynet01 what version of HA are you on?

does it help if you remove `compact_header: false` from the iPad exception? Since you're hiding the header it is unnecessary and might be the culprit.

**Comment by maykar** [comment]
Try this:
```yaml
cch:
  exceptions:
    - conditions:
        user_agent: iPad
      config:
        header: false
        hide_tabs: ""
        menu: show
        notifications: show
        options: show
        swipe: true
        swipe_amount: '20'
        swipe_animate: swipe
        swipe_prevent_default: true
        swipe_skip: '3'
        voice: show
  hide_help: true
  hide_tabs: '4'
  options: clock
```
