### ISSUE TITLE
[Feature Request] Group exceptions

### ISSUE THREAD

**Issue by carldebilly** [maykar/compact-custom-header#197]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the _User/Device Exceptions_ feature, but instead of targetting specific users or specific devices, I would like to target groups. This way I won't have to change the UI when I add or remove a user from the system: I'll just put them in the right group.

**Describe the solution you'd like**
``` yaml
cch:
  menu: overflow
  options: clock
  voice: hide
  clock_format: 12
  exceptions:
    - conditions:
        group: admin # HA build-in "admin" group
      config:
        voice: show
        options: clock
        clock_format: 24
    - conditions:
        group: roommates # custom user group
      config:
        options: clock
        clock_format: 12
        hide_tabs: 4,5,9

```

Base on this: https://developers.home-assistant.io/blog/2019/03/11/user-permissions.html
