### ISSUE TITLE
Background image no longer fills view on HA 0.99 +

### ISSUE THREAD

**Issue by Bergasha** [maykar/compact-custom-header#199]
## Describe the issue:
The header has lost  transparent background on 0.99

## Config YAML:

```
cch:
  active_tab_color: red
  all_tabs_color: white
  background: 'rgba(0,0,0,0)'
  clock_am_pm: false
  default_tab: '0'
  hide_help: true
  hide_tabs: '9,2,7'
  main_config: true
  notifications: overflow
  options: clock
  swipe: true
  swipe_amount: '30'
  swipe_animate: fade
  tab_color:
    '0': white
    '1': white
  tab_indicator_color: red
  voice: hide


```
## HA and/or Browser Error:
Still working fine just not how I would like it to look

## Versions and Browser:
CCH 1.3.6 HA 0.99.0b0 
Chrome and Wallpanel on android 

![Untitled](https://user-images.githubusercontent.com/25044200/64903136-c6f8be00-d6f6-11e9-93c8-365355d47f84.jpg)

Storage Mode
