### ISSUE TITLE
Theme changing causes browser tab to become unresponsive

### ISSUE THREAD

**Issue by coasting24** [maykar/compact-custom-header#202]
## Describe the issue:
I noticed this issue recently where the browser will hang if I do the following steps when Compact Custom Header is enabled:

Click on my Profile and change the theme
Click on Overview to navigate to the Lovelace home page
Click on any other tab or sidebar icon
When this happens the CPU usage of the Chrome renderer process rapidly increases to almost 200% and the page becomes unresponsive and I need to kill the process. This happens in Chrome and Safari on my Mac and Chrome on my Android phone (on the phone the whole browser becomes unresponsive and I need to force stop it).

Disabling Compact Custom Header stops this from happening. It also doesn’t happen if I refresh the page after changing the theme (as long as this is done before trying to navigate to another tab).

I am using CCH 1.3.6 on Home Assistant 0.98.5

## Config YAML:

```yaml
none
```
## HA and/or Browser Error:

none
## Versions and Browser:

I am using CCH 1.3.6 on Home Assistant 0.98.5

**Comment by maykar** [comment]
You have no config for cch and are just using the defaults or did you just not include your config?

**Comment by coasting24** [comment]
Didn't find it relevant but here you are:
```yaml
cch:
  menu: overflow
  options: clock
  voice: hide
  clock_format: 24
  exceptions:
    - conditions:
        user: xxxxx
      config:
        options: clock
        clock_format: 24
    - conditions:
        user: xxxxx
#        user_agent: Mobile
#        media_query: "(max-width: 600px)"
      config:
        options: clock
        hide_tabs: '9,10'        
        clock_format: 24
#        kiosk_mode: true
    - conditions:
        user: xxxx
#        user_agent: Mobile
#        media_query: "(max-width: 600px)"
      config:
        options: clock
        hide_tabs: '9,10'        
        clock_format: 24
#        kiosk_mode: true
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
```

**Comment by maykar** [comment]
Very relevant, I can't test what's wrong without knowing what your using. If others have the same problem I can look at similarities in configs to rule things out. Closing this one since the other exists, but your config should help me figure this one out.

**Comment by coasting24** [comment]
Here you are.
```yaml
cch:
  menu: overflow
  options: clock
  voice: hide
  clock_format: 24
  exceptions:
    - conditions:
        user: xxxxx
      config:
        options: clock
        clock_format: 24
    - conditions:
        user: xxxxx
#        user_agent: Mobile
#        media_query: "(max-width: 600px)"
      config:
        options: clock
        hide_tabs: '9,10'        
        clock_format: 24
#        kiosk_mode: true
    - conditions:
        user: xxxx
#        user_agent: Mobile
#        media_query: "(max-width: 600px)"
      config:
        options: clock
        hide_tabs: '9,10'        
        clock_format: 24
#        kiosk_mode: true
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
```
