### ISSUE TITLE
Hidden Tab Redirect Not Working in iOS Beta

### ISSUE THREAD

**Issue by mrgadget** [maykar/compact-custom-header#205]
## Describe the issue:
Moved to the HA iOS Beta app and CCH no longer redirects away from my hidden 'conig' tab (tab 0). ie, on a fresh load tab 0 content is shown (when it shouldn't be on a mobile device).  The correct icons are hidden in the header - which indicates the correct conditions block is being hit, it's just behaving like the 'redirect' option isn't working.

Not a major issue - just thought you'd like to know about it.

## Config YAML:

```yaml
cch:
  background: '#003A99'
  clock_am_pm: false
  clock_date: false
  clock_format: '24'
  disable: false
  exceptions:
    - conditions:
        user: Ben
        user_agent: Mobile
      config:
        hide_tabs: '0,1,2,6'
    - conditions:
        user: Ben
      config:
        hide_tabs: '6'
        menu: show
        options: show
  header: true
  hide_tabs: '0,1,2'
  main_config: true
  menu: hide
  options: hide
  redirect: true
  voice: hide
```
## HA and/or Browser Error:

No errors, able to simply browse to another tab, then can't get back again (expected).

## Versions and Browser:

HA 0.97.2
CCH 1.3.1
iOS Beta App
YAML or Storage Mode? No idea...
