### ISSUE TITLE
Browser Hangs in Home Assistant iOS App (2.0) with CCH > 1.3.5

### ISSUE THREAD

**Issue by chipriley** [maykar/compact-custom-header#210]
## Describe the issue:
When I upgrade CCH to anything higher than 1.3.5 (including 1.4.0), any navigation using the sidebar will result in the official iOS app (2.0) hanging indefinitely.  I have to force close the app to be able to use it.  I've even flushed the frontend cache in the app settings.  If I revert to 1.3.5 via HACS on a desktop, functionality is restored and everything works.  [In this video](https://share.icloud.com/photos/0wdKIwzUGHzo_DD2Mk34baZxw), you can see the animated icons on the Home tab stop when I select HACS from the sidebar. You can also see the trimmed portion at the bottom when I scroll down to my thermostats.

## Config YAML:

```yaml
cch:
  menu: overflow
  background: true
  options: clock
  voice: hide
  clock_format: 12
  clock_am_pm: true
  clock_date: true
```
## HA and/or Browser Error:

Can't debug within the app.  
## Versions and Browser:

CCH Version: >1.3.5
HA 0.99.2 (Hassio)
Home Assistant 2.0 Beta on iOS
YAML Mode
