### ISSUE TITLE
Swipe not working on iPhone

### ISSUE THREAD

**Issue by ebnerjoh** [maykar/compact-custom-header#212]
## Describe the issue:
Swipe not working on iPhone for User1

## Config YAML:

```
cch:
  clock_am_pm: false
  clock_format: '24'
  exceptions:
    - conditions:
        user: User1
        user_agent: iPhone
      config:
        hide_tabs: '7,8'
        menu: show
        notifications: show
        show_tabs: []
        voice: hide
        hide_config: true
        options: hide
        swipe: true
        swipe_amount: '20'
        swipe_animate: fade
        swipe_prevent_default: true
    - conditions:
        user: User2
      config:
        clock_format: '24'
        date_locale: de
        hide_config: true
        hide_tabs: '7,8'
        menu: hide
        notifications: show
        options: hide
        show_tabs: []
        swipe: true
        swipe_amount: '20'
        swipe_animate: fade
        voice: hide
    - conditions:
        user: User3
      config:
        show_tabs: []
        voice: hide
        notifications: show
        disable_sidebar: true
        header: true
        hide_config: true
        options: hide
        hide_tabs: '2,3,4,5,6,7'
        swipe: true
        swipe_amount: '20'
        swipe_animate: fade
        swipe_wrap: true
        menu: hide
  hide_help: true
  hide_tabs: '7,8'
  hide_unused: true
  swipe: true
  swipe_animate: fade
  voice: hide
  swipe_amount: '20'
```

## Versions and Browser:

CCH: 1.4.0
Home Assistant: 0.99.3
iOS 13 with Home Assistant App
YAML
