### ISSUE TITLE
Header not completely removed in kiosk mode since CCH 1.4.1

### ISSUE THREAD

**Issue by noxhirsch** [maykar/compact-custom-header#214]
## Describe the issue:
When the header gets removed in kiosk mode, a banner of background with the height of the original header stays - like in this screenshot: https://github.com/maykar/compact-custom-header/issues/206#issuecomment-535230082

## Config YAML:

```yaml
cch:
  clock_format: 24
  edit_mode_show_tabs: true
  exceptions:
    - conditions:
        media_query: '(max-width:600px)'
        query_string: kiosk
      config:
        default_tab: []
        kiosk_mode: true
        menu: hide
        notifications: show
        options: show
        show_tabs: '10'
        swipe: false
        view_css: 'margin-top:-8px;'
        voice: hide
  hide_help: true
  hide_tabs: '9, 10'
  menu: hide
  notification: show
  redirect: false
  sidebar_closed: true
  swipe: true
  swipe_amount: '33'
  swipe_animate: swipe
  type: 'custom:compact-custom-header'
  voice: hide
```
## HA and/or Browser Error:
![header3](https://user-images.githubusercontent.com/30938717/65822274-90b45600-e241-11e9-8772-07fd22b53465.PNG)

## Versions and Browser:
CCH 1.4.1 
HA 99.3
Chrome up2date
Storage Mode

**Comment by maykar** [comment]
Remove  `default_tab: []`
```yaml
cch:
  clock_format: 24
  edit_mode_show_tabs: true
  exceptions:
    - conditions:
        media_query: '(max-width:600px)'
        query_string: kiosk
      config:
        kiosk_mode: true
        menu: hide
        options: show
        show_tabs: '10'
        swipe: false
        view_css: 'margin-top:-8px;'
        voice: hide
  hide_help: true
  hide_tabs: '9, 10'
  menu: hide
  redirect: false
  sidebar_closed: true
  swipe: true
  swipe_amount: '33'
  swipe_animate: swipe
  type: 'custom:compact-custom-header'
  voice: hide
```
