### ISSUE TITLE
CCH not working with Edge browser

### ISSUE THREAD

**Issue by IgorMarkovic** [maykar/compact-custom-header#216]
## Describe the issue:
It looks like cch is not working in an Edge browser. In de dev console I see the message 'SCRIPT5022: SCRIPT5022: Expected identifier, string or number' as soon as I add the js file to my Lovelace configuration and reload the page. After looking at the js file I see a lot of … (I think it's called 'Spread syntax') which, I think, is not fully supported in Edge: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals
Could that be the problem? Or should it work in Microsoft Edge?

## Config YAML:
```yaml
resources:
  - type: module
    url: /local/custom-compact-header/compact-custom-header.js?v=0.0.1
cch:
  clock_date: true
  clock_format: '24'
  date_locale: nl-NL
  options: clock
  swipe: true
  swipe_amount: '10'
  swipe_animate: swipe
  swipe_wrap: false
  voice: hide
```

## HA and/or Browser Error:
SCRIPT5022: SCRIPT5022: Expected identifier, string or number

## Versions and Browser:
CCH 1.4.1
Debian with Home Assistant 0.98.5
Microsoft Edge: NOT working, Chrome: Working
Storage Mode
