### ISSUE TITLE
No options switches in CCH Settings

### ISSUE THREAD

**Issue by QbaF** [maykar/compact-custom-header#229]
## Describe the issue:
No visible switches for options
![image](https://user-images.githubusercontent.com/57077178/67645882-8ada8f00-f92b-11e9-8f47-62082012c1ba.png)

## Config YAML:

```yaml
resources:
  - type: module
    url: /community_plugin/compact-custom-header/compact-custom-header.js
```
## HA and/or Browser Error:
No corresponding errors in logs

## Versions and Browser:
CCH: 1.4.1; HA: 0.100.3
Google Chrome:77.0.3865.120; Firefox 70.0
Storage Mode
