### ISSUE TITLE
CCH breaks when only using a single view/panel

### ISSUE THREAD

**Issue by IDmedia** [maykar/compact-custom-header#230]
## Describe the issue:
CCH breaks when using only one view/panel. Tested on multiple HASS installs with no third party modules installed.

## Config YAML:
```
# Compact Custom Header
cch:
  swipe: true
  swipe_wrap: true
  swipe_animate: fade
  swipe_amount: 30
  voice: hide
  options: clock
  clock_format: 24

# Views
views:
  - title: Home
    panel: true
    cards:
      ....
```
## HA and/or Browser Error:
```
Uncaught TypeError: Cannot read property 'querySelector' of null
    at CompactCustomHeader.scrollTabIconIntoView (compact-custom-header.js:346)
    at compact-custom-header.js:265
    at Array.forEach (<anonymous>)
    at MutationObserver.callback (compact-custom-header.js:213)
```

## Versions and Browser:
CCH 1.4.5
Google Chrome 78 (Latest)
Yaml-mode
