### ISSUE TITLE
Papertabs is null

### ISSUE THREAD

**Issue by febalci** [maykar/compact-custom-header#232]
## Describe the issue:

Getting TypeError: paperTabs is null errors

## Config YAML:

```yaml
cch:
  clock_date: true
  clock_format: '24'
  options: clock
```
## HA and/or Browser Error:

HA log: https://XXXX.XXXX.com:8123/community_plugin/compact-custom-header/compact-custom-header.js:346:22 TypeError: paperTabs is null
## Versions and Browser:

HA 0.101.0
HACS CCH 1.4.5

Firefox 70.0  (64 bit)

HA frequently gives this error. Still i can see the date and clock on the header.
