### ISSUE TITLE
Cannot read property 'newSidebar' of undefined

### ISSUE THREAD

**Issue by shreram** [maykar/compact-custom-header#234]
## Describe the issue:

Looks recent upgrade broke my setup. I haven't changed any settings in awhile. I am using Yaml mode.

## Config YAML:

```yaml
cch:
  options: clock
  clock_date: true
  voice: hide
  clock_format: 12
  swipe: true
  active_tab_color: rgb(181, 142, 49)
  tab_indicator_color: rgb(181, 142, 49)
  notify_indicator_color: "#00FFFF" # the notifications indicator
  notify_text_color: brown # number inside notifications indicator
  hide_help: true
  hide_config: true
  conditional_styles:
    - template:
        tab:
          0:
          - icon: >
              if ((entity["device_tracker.life360_rk"].state == "home") && (entity["device_tracker.life360_rc"].state == "not_home")) "mdi:account-tie";
              else if ((entity["device_tracker.life360_rc"].state == "home") && (entity["device_tracker.life360_rk"].state == "not_home")) "mdi:account-star";
              else if ((entity["device_tracker.life360_rc"].state == "home") && (entity["device_tracker.life360_rk"].state == "home")) "mdi:account-group-outline";
              else "mdi:car";
    - entity: notifications
      condition:
        state: false      # When there are no notifications...
      button:             # hide notifications button.
        notifications:
          hide: true

```
## HA and/or Browser Error:

Uncaught TypeError: Cannot read property 'newSidebar' of undefined
    at notificationCount (compact-custom-header.js:1152)
    at CompactCustomHeader.conditionalStyling (compact-custom-header.js:1186)
    at CompactCustomHeader.styleHeader (compact-custom-header.js:531)
    at CompactCustomHeader.run (compact-custom-header.js:118)
    at compact-custom-header.js:1830
notificationCount @ compact-custom-header.js:1152
conditionalStyling @ compact-custom-header.js:1186
styleHeader @ compact-custom-header.js:531
run @ compact-custom-header.js:118
(anonymous) @ compact-custom-header.js:1830

## Versions and Browser:

Installed version: | 1.4.7
-- | --

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.4
timezone | America/Chicago
version | 0.100.3
virtualenv | false
