### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by grewhit25** [maykar/compact-custom-header#236]
## Describe the issue:

CCH module not loading correctly.
I receive 'Uncaught TypeError' error below even with the simplest of cch config. The error is still reported when cch: is commented out and also same when url + type commented out.

All has been working fine up until a few days ago after an Home Assistant update via watchtower.
I am running the latest beta build which I do accept might be the culprit.

## Config YAML:

```yaml
resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
:
cch:
  menu: overflow
  options: clock
  clock_date: true
  voice: hide
  clock_format: 12

```
## HA and/or Browser Error:

```log

2019-11-12 16:16:40 ERROR (MainThread) [frontend.js.latest.201911080] https://<my_duckdns.org>/community_plugin/compact-custom-header/compact-custom-header.js:317:30 Uncaught TypeError: Cannot read property 'querySelector' of null
```

CCH is not functional.

## Versions and Browser:

CCH version 1.4.7
Home Assistant 0.102.0.dev20191112
Browsers are Chrome, MS Edge, Mobile App - all with the same result.
Lovelace mode:yaml
