### ISSUE TITLE
Navigation missing in 1.4.9

### ISSUE THREAD

**Issue by allanpersson** [maykar/compact-custom-header#239]
## Describe the issue:
Main navigation is missing in 1.4.9 on mobile. Reinstalling 1.4.7 fixes the problem. Can't seem to find any breaking changes from .7 to .9
![Screenshot_20191115-210029_Home Assistant](https://user-images.githubusercontent.com/46043392/68972295-c4484100-07eb-11ea-8fb0-11778aed4211.jpg)

## Config YAML:
```
cch:
  clock_am_pm: false
  clock_date: true
  clock_format: '24'
  exceptions: []
  main_config: true
  options: clock
  voice: overflow

```

## Versions and Browser:
1.4.9 / 0.102.0b1
Vivaldi and native Android app

**Comment by allanpersson** [comment]
Updated to 0.102.0b2 and it's still a bug there 🙏

**Comment by maykar** [comment]
Take the voice button out of overflow:
```
cch:
  clock_am_pm: false
  clock_date: true
  clock_format: '24'
  exceptions: []
  main_config: true
  options: clock
```

There were recent changes to the voice element in HA's betas. I put in a quick fix, but voice is not working as a clock or in the overflow menu. Please see thread here for more info:

https://community.home-assistant.io/t/compact-custom-header/83716/1327
