### ISSUE TITLE
Error message in log on Home Assistant 0.102.3

### ISSUE THREAD

**Issue by miljume** [maykar/compact-custom-header#242]
## Describe the issue:
I receive an error at every restart of Hass.IO

> https://*host*:8123/local/community/compact-custom-header/compact-custom-header.js?v=0.0.1:317:30 Uncaught TypeError: Cannot read property 'querySelector' of null

## Config YAML:

```
menu: show
notifications: clock
voice: hide
options: show
clock_format: 24
clock_am_pm: false
clock_date: false
exceptions:
  - conditions:
      user_agent: Mobile
    config:
      menu: overflow
      notifications: overflow
      swipe: true
      swipe_animate: swipe
```
## HA and/or Browser Error:

See above, CCH functions despite that

## Versions and Browser:

CCH 1.4.9, Hass.IO 0.102.3, Chrome Version 78.0.3904.97 (Mac)
