### ISSUE TITLE
Conditional styles for Kiosk user

### ISSUE THREAD

**Issue by theOrakle** [maykar/compact-custom-header#244]
## Describe the issue:
I'm attempting to lock down my iPad "Kiosk" users when the alarm panel is armed.  I see "Conditional styles may be used inside exceptions.", but I'm failing to get it to work.  The YAML below is outside of the exception, but I would greatly appreciate an inside example as I have failed. 

## Config YAML:

```yaml
cch:
  menu: hide
  voice: hide
  notifications: hide
  options: hide
  disable_sidebar: true
  exceptions:
  - conditions:
      user: Administrator
    config:
      disable: true
  - conditions:
      user: Kiosk
    config:
      options: clock
  conditional_styles:
  - entity: alarm_control_panel.home_assistant
    condition:
      state: "armed_night"
    tab:
      1:
        hide: true
```
## Versions and Browser:

CCH:  1.4.9
HA: .103.0

Safari

YAML

Ideally, I would like to hide all tabs and just show the alarm panel.  I realize I may need to create another tab with just the alarm panel on it in that case.
![image](https://user-images.githubusercontent.com/37029980/70849663-52453500-1e47-11ea-9f8d-b537ea67c070.png)
