### ISSUE TITLE
Can't start using card

### ISSUE THREAD

**Issue by advokatb** [maykar/compact-custom-header#25]
Hi.
This is the start of my config
```
resources:
# https://github.com/maykar/compact-custom-header
# https://community.home-assistant.io/t/compact-custom-header-custom-user-device-views/83716
  - url: /local/js/compact-custom-header.js?v=6
    type: js  

title: "  "
background: center / cover no-repeat url("/local/images/back.png") fixed
excluded_entities:
  - weblink.router
views:
  - icon: mdi:home-variant
    title: Главная
    path: main
    background: center / cover no-repeat url("/local/images/back.png") fixed
    theme: dark_theme
    cards:
      - type: custom:compact-custom-header
        voice: false
        header: false
        clock: notification
        clock_format: 24

      - type: custom:card-modder
        card: 
          type: entity-filter
          entities:
            - device_tracker.igor
            - device_tracker.jana
            - device_tracker.vika
            - device_tracker.lesha
          state_filter:
            - 'home'
          card:
            type: glance
            title: КТО ДОМА?
        style:                 
          background-image: url("/local/images/cardbackK.png")
          background-repeat: no-repeat
          background-color: rgba(50,50,50,0.3)
          background-size: 100% 68px
          border-radius: 20px
          border: solid 1px rgba(100,100,100,0.3)
          box-shadow: 3px 3px rgba(0,0,0,0.4)    
```
But I can't make icons of all my views start showing in one row with menu.

What am I doing wrong?
Thanks.
