### ISSUE TITLE
TypeError: notify_dot is null

### ISSUE THREAD

**Issue by tjorim** [maykar/compact-custom-header#27]
Home Assistant 0.86.3
compact-custom-header 0.2.9

```
compact-custom-header.lib.js:236:9
TypeError: notify_dot is null
```

**Comment by maykar** [comment]
Does the card work despite the error? What does your config look like? Have you done a hard refresh?

**Comment by moskovskiy82** [comment]
Same here. Do the other cards have to be placed under the custom header?

```
views:
  - title: Home
    id: main
    icon: mdi:home-assistant
    cards:
      - type: custom:compact-custom-header
        header: false
        menu: true
        notification: true
        voice: false
        options: false
        tabs: true
        clock: notification
        clock_format: 24
        disable: false
      - type: vertical-stack
        cards:
        - type: conditional
          conditions:
```



2019-02-03 01:01:11 ERROR (MainThread) [frontend.js.latest.201901211] https://www.xxx.ru:8123/frontend_latest/xxx9235853b66c6b78f9.chunk.js:3254:365 Uncaught TypeError: Cannot read property 'replaceChild' of null
