### ISSUE TITLE
Panel: true issue

### ISSUE THREAD

**Issue by thib5** [maykar/compact-custom-header#28]
i'm trying to do something like that : but as soon as i uncomment "panel:true: nothing  display 

```
  - title: IframPanel
#   panel: true
    cards:
    - type: custom:compact-custom-header
      header: false
      background_image: true

    - type: iframe
      url: /local/test2.html
      aspect_ratio: 5%

```
