### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Tontze** [maykar/compact-custom-header#47]
**Describe the bug**

After updating no longer works. Did what was told in readme. 

**Config**
```
  - id: 50
    title: Test Page
    background: center / cover no-repeat url("/local/background-abstract.jpg") fixed
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        options: clock
        voice: hide
        clock_format: 24
```
```
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.0.0b1
    type: module
```

**Error**

in homeassistant.log 

``` 
:8123/lovelace/5:0:0 Uncaught SyntaxError: The requested module './compact-custom-header.js' does not provide an export named 'html'

```

**Version**
0.87.1 Home Assistant Version
1.0.0b1 Compact Custom Header Version
Google chrome Browser type and version
