### ISSUE TITLE
Hiding tabs doesn't work

### ISSUE THREAD

**Issue by morrisb74** [maykar/compact-custom-header#48]
**Describe the bug**
Trying to hide tabs under a specific user

**Config**
```
exceptions:
  - conditions:
      user: Test User
    config:
      menu: hide
      voice: hide
      notifications: hide
      options: hide
      hide_tabs: 'Dev,11,10'
```

**Error**
No error but it still shows the tabs under the specific user

**Screenshots**

**Version**
 0.87.1 
1.0.0b1
Chrome & Firefox

**Additional context**
Would  love to be ableto hide my Dev & Automations tab for the non tech users :)
