### ISSUE TITLE
Exceptions not working with user_agent: mobile.  v1.0.0b2

### ISSUE THREAD

**Issue by pbeckcom** [maykar/compact-custom-header#53]
**Describe the bug**
I have the config set to disable custom compact header on mobile user agents but it's not disabling.  I tried hiding the notification icon as well and it appears the exception is simply not applying to the mobile user agent, or it's not detecting the agent properly.

I have already cleared cache and that has not helped.

**Config**
```
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
        options: clock
        voice: hide
        clock_format: 12
        clock_am_pm: true
        exceptions:
          - conditions:
              user_agent: mobile
            config:
              disable: true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/46651681/52864096-0d555280-30ff-11e9-99c2-3d869e4eb6e4.png)

**Version**
Home Assistant Version 87.0
Compact Custom Header Version  1.0.0b2
Browser type and version Chrome/72.03626.105 Mobile
