### ISSUE TITLE
Need an example for container cards

### ISSUE THREAD

**Issue by shreram** [maykar/compact-custom-header#62]
## Describe the bug:

This is not a bug but a question rather. Could you please additional examples for the following.

**To use with panel view place this card inside a "container card" with the panel card (vertical stack card, layout-card, etc.), otherwise this card isn't "displayed" and won't load.**

In the following code snippet, some sensor values were not shown when I used 'custom:useful-markdown-card'.

I have also used 'layout-card' from 'thosmaslaven' and after switching this UI then all the layouts that I set from that card were messed up.

I commented out all the lines where 'panel: true' was set.

## Config:

```
  - url: /local/custom-lovelace/maykar/compact-custom-header.js?v=0.0.1
    type: module
views:
  - id: 0  # Automatically created id
    icon: mdi:home-assistant
    title: Main view
    # panel: true
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        options: clock
        voice: hide
        clock_format: 12
      - id: 92ad9f49f71e4735b07e512c06ad6722 # i added this
        type: custom:layout-card
        layout: horizontal
        cards:
          - id: f2f76e770b8f43cdb249d90a2b16c3c6  # Automatically created id
            type: custom:useful-markdown-card
            title: Today
            content: >

              [[ sensor.friendly_date.state ]]


              ***[[ sensor.tmpl_cal_primary.state ]]***


              **Weather** - [[sensor.pws_weather_1d.state]]


              High : **[[ sensor.dark_sky_daytime_high_temperature_0.state ]]° F**
              Overnight Low :  **[[ sensor.dark_sky_overnight_low_temperature_0.state ]]° F**


              Last notification: **[[ sensor.appd_notify_message.state ]]**


          - id: f63e113c5e324a808af460a605bac84d # i added this
            type: entities
            title: Control Panel
            show_header_toggle: false
            columns: 4
            entities:
              - entity: input_boolean.where_are_the_kids
                name: Where Is Everyone?
              - entity: input_boolean.show_upcoming_events
                name: Show upcoming events
              - type: weblink
                name: Automation Schedule
                url: /lovelace/3
                icon: mdi:theme-light-dark
              - type: weblink
                name: Weather Maps
                url: /lovelace/2
                icon: mdi:weather-lightning-rainy
              - type: weblink
                name: Cameras
                url: /lovelace/6
                icon: mdi:cctv  
              - entity: script.refresh_wink

```

## Versions:

Version : 1.0.1b2

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.2
timezone | America/Chicago
version | 0.88.2
virtualenv | false

mode | yaml
-- | --
resources | 15
views | 8

**Comment by maykar** [comment]
You've got options. Work with whichever works better for you. Here's a couple of examples:

You can just put it inside the layout card:
```
cards:
  - id: 92ad9f49f71e4735b07e512c06ad6722 # i added this
    type: custom:layout-card
    layout: horizontal
    cards:
    - type: custom:compact-custom-header
      main_config: true
      menu: overflow
      options: clock
      voice: hide
      clock_format: 12
```
You could put it in a vertical stack with layout card:
```
cards:
  - type: vertical-stack
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        options: clock
        voice: hide
        clock_format: 12
      - id: 92ad9f49f71e4735b07e512c06ad6722 # i added this
        type: custom:layout-card
        layout: horizontal
        cards:
```

**Comment by maykar** [comment]
I'll add this to the readme as well.

**Comment by shreram** [comment]
How to troubleshoot this on a mobile device?

Following snippet works fine when I browse on my tablet and laptop. But on my phone I get an error
for '**Custom element doesn't exist: layout-card.**'

```
  - id: 1  # Automatically created id
    icon: mdi:lightbulb-on-outline
    title: Switches Lights view
    panel: true
    path: lights_switches
    theme: done1
    cards:
      # - type: custom:compact-custom-header
      #   header: true
      - id: 55608c01f1c540b28138c20eda69baff  # Automatically created id
        # type: glance
        type: custom:layout-card
        layout: horizontal
        cards:
          - id: ad2d5336-16ee-4240-a059-f8e42a1c1e10  # I created id
            type: glance
            title: Switches
            columns: 3
            entities:
              - type: entity-button
                entity: switch.ge_12722_onoff_relay_switch_switch_3
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - type: entity-button
                entity: switch.ge_12722_onoff_relay_switch_switch_2
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - type: entity-button
                entity: switch.ge_12722_onoff_relay_switch_switch_4
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - type: entity-button
                entity: switch.leviton_dzs151lz_switch_switch
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - type: entity-button
                entity: switch.ge_12722_onoff_relay_switch_switch
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
          - id: 34b5b700f9204892bc35f5ffbf7e7896  # Automatically created id
            type: entities
            title: Lights
            show_header_toggle: false
            entities:
              - entity: light.hallway_light_bulb_one
                secondary_info: last-changed
                name: Hallway light One
              - entity: light.notused_light
                secondary_info: last-changed
                name: Hallway light Two    
              - entity: light.shreya_bedroom_bulb
                secondary_info: last-changed
              - entity: light.steps_light
                icon: mdi:stairs
                secondary_info: last-changed
                name: Staircase light
              - entity: light.garage_light
                secondary_info: last-changed
          - break
          - id: b448d8fbbda54e2c9e75e806964d0403  # Automatically created id
            type: custom:vertical-stack-in-card
            cards:
              - type: entities
                title: Outlets
                show_header_toggle: false
                entities:
                  - entity: input_boolean.show_addl_outlets
              - type: glance
                columns: calc(100% / 3)
                show_header_toggle: false
                entities:
                  - type: entity-button
                    # entity: switch.google_home_outlet
                    entity: switch.bedroom_light
                    name: Master Bedroom light
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                    icon: mdi:power-socket-us  
                  - type: entity-button
                    entity: switch.7684600084f3eb9c8745
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: entity-button
                    entity: switch.51163006bcddc2070fe5
                    name: Family room light One                    
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: entity-button
                    entity: switch.uverse_outlet
                    name: Family room light Two
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
          - break
          - id: 63073348cb0746ac99b53c82d7006264  # Automatically created id
            type: custom:vertical-stack-in-card
            cards:
              - type: entities
                title: Hubs and Sensors
                show_header_toggle: false
                entities:
                  - entity: binary_sensor.winkhub
                  - entity: zwave.aeotec_zw090_zstick_gen5_us
              - type: glance
                columns: 3
                entities:
                  - entity: sensor.tmpl_garage_entry_door_sensor_status
                    name: Garage Sensor
                    hold_action: more-info
                  - entity: sensor.tmpl_garage_entry_door_sensor_battery
                    name: Battery
                  - entity: sensor.tmpl_second_floor_hallway_sensor_status
                    name: Hallway Sensor
                  - entity: binary_sensor.motion_sensor_opened
                    name: Opened?
                  - entity: sensor.tmpl_second_floor_hallway_motion_sensor_battery
                    name: Battery
          - id: 0472524f6a264111a32be5b30bb050a8  # Automatically created id
            type: conditional
            conditions:
              - entity: input_boolean.show_addl_outlets
                state: "on"
            card:
              type: entities
              title: Always On Outlets
              show_header_toggle: false
              entities:
                - entity: switch.0720034284f3eb852067_1
                - entity: switch.0720034284f3eb852067_2
          - type: custom:compact-custom-header    
            header: true
```
