### ISSUE TITLE
Notification badge not displayed correctly when set to overflow

### ISSUE THREAD

**Issue by Valiceemo** [maykar/compact-custom-header#63]
## Describe the bug:
When notifications is set to `overflow` the badge is not displayed correctly, as seen on this [community forum post](https://community.home-assistant.io/t/compact-custom-header-custom-user-device-views/83716/444?u=valiceemo)

## Config:

```yaml
      - type: custom:compact-custom-header
        main_config: true
        menu: hide
        options: clock
        voice: overflow
        notifications: overflow
        header: true
```

## Error:
No errors logged

## Versions:
compact-custom-card v1.0.1b3
HA v 0.88.1

![smartselect_20190302-084502_samsung internet beta](https://user-images.githubusercontent.com/14888143/53688610-5384f580-3d3e-11e9-90e1-e64108965e14.jpg)
