### ISSUE TITLE
background bottom

### ISSUE THREAD

**Issue by PeteCondliffe** [maykar/compact-custom-header#69]
Firstly I would just like to say this is a awesome addition lovelace and thanks for all the work that's gone into this.

## Describe the bug:
With `header: false` and `background_image: true` the background does not stretch to the full page when using background gradient. I have also tried adding a image in case its an issue with using gradient but get the same issue.
with `header: true` the background covers the whole screen as expected
This is logging in with the user called bedroom. 

View with the issue
![Capture](https://user-images.githubusercontent.com/37262524/54089573-35348080-4362-11e9-9861-9b4ec03a09bc.PNG)

A test view with way less going on, which is the yaml below
![Capture](https://user-images.githubusercontent.com/37262524/54089599-788eef00-4362-11e9-975b-a35507ab061c.PNG)

## Config YAML:
```
title: Dev
path: dev
theme: midnight
#panel: true
icon: mdi:script
background: radial-gradient(circle, rgba(84,34,84,1) 0%, rgba(0,0,0,1) 100%)

cards:
  - type: custom:compact-custom-header
    main_config: true
    header: true
    background_image: true
    menu: hide
    notifications: hide
    voice: hide
    options: hide
    hide_tabs: 9,10,11,12
    exceptions:

      - conditions:
          user: bedroom
        config:
          header: false
          hide_tabs: 0,1,2,3,4,5,6,7,8,9,10,11
  

  - type: custom:button-card
    entity: media_player.living_room_tv
    action: more_info
    name: TV Remote
```

## HA and/or Browser Error:
No errors in Chrome

## HA, Card, and Browser Versions:
Using YAML Mode
HA Version: 89.1
compact-custom-header: 1.0.1b3
