### ISSUE TITLE
 Margin on top (89.1)

### ISSUE THREAD

**Issue by Bastiencc** [maykar/compact-custom-header#71]
## Describe the bug:

Hello

First, thanks for the great work !
I just upgrade to 89.1, and I get this margin on top (look at screenshot)

## Config YAML:

 ```yaml       
     - type: 'custom:compact-custom-header'
        main_config: true
        # disable: true
        menu: overflow
        notifications: overflow
        voice: hide
        options: overflow
        clock_format: 24
        exceptions:
          - conditions:
              user_agent: Windows
            config:
              disable: true
          - conditions:
              user: Marion
            config:
              hide_tabs: 5
```

## HA and/or Browser Error:

no error

## HA, Card, and Browser Versions:

HA : 89.1

![2019-03-11 08 16 28](https://user-images.githubusercontent.com/37021892/54106972-212b6600-43d8-11e9-9bec-9175b44c1ad1.jpg)
