### ISSUE TITLE
Time doesn't appear when on top of Menu Icon

### ISSUE THREAD

**Issue by xicoxicao** [maykar/compact-custom-header#73]
## Describe the bug:
Time stamp does not appear on top of the menu button as requested and date does not appear. When changing time stamp on top of voice button there is no issue
![image](https://user-images.githubusercontent.com/34278789/54129972-61eea380-4407-11e9-96aa-4fb234dd889f.png)
![image](https://user-images.githubusercontent.com/34278789/54129985-687d1b00-4407-11e9-983e-f494e9217034.png)

## Config YAML:
```yaml
exceptions:
  - config:
      hide_tabs: '2'
    conditions:
      user_agent: Mobile
menu: clock
voice: hide
clock_format: '12'
clock_am_pm: false
type: 'custom:compact-custom-header'
clock_date: true
main_config: true
```
## HA and/or Browser Error:
Other than this the card is working very well. I don't get an error in HA and I'm not sure what you want to see from the browser. I do get this messeage "Unable to find icon for domain counter (0) d39aefe3f62fd41b4b8b.chunk.js:1441" but don't know what else to give you

## HA, Card, and Browser Versions:
HA 0.89 card1.01.1b3 chrome 72.0.3626.119 and firefox 65.0.2

And let me thank you for the excelent work
