### ISSUE TITLE
Clicking the menu icon doesn't toggle the menu but clicking the menu text does

### ISSUE THREAD

**Issue by jhanssen** [maykar/compact-custom-header#74]
## Describe the bug:
Clicking the actual hamburger menu icon doesn't toggle the menu, clicking the text "Menu" does. When clicking the icon my graph cards seem to redraw but the menu doesn't slide in/out of view.

## Config YAML:
```yaml
- type: custom:compact-custom-header
  menu: overflow
  options: clock
  voice: hide
```
## HA and/or Browser Error:
No errors in the HA logs or in the dev console.

## HA, Card, and Browser Versions:
HA 0.89.1
Card 1.0.1b3
Browser Chrome 72.0.3626.81, same thing happens in Safari 12.0.3.
