### ISSUE TITLE
0.90.0b2 broke the CCH

### ISSUE THREAD

**Issue by VDRainer** [maykar/compact-custom-header#78]
## Describe the bug:
All tabs show up on all clients after beta 0.90.0b2
Back on 0.90.0b1, everythins OK.

## Config YAML:
```yaml
- type: custom:compact-custom-header
  menu: overflow
#  background_image: true
  exceptions:
#    - conditions:
#        user_agent: Mobile
#      config:
#        options: hide
#        hide_tabs: 13,14,15,16,17
    - conditions:
        user: TPad
      config:
        menu: hide
        options: hide
        hide_tabs: 0,1,2,3,4,5,6,7,8,9,10,11,12

```
## HA and/or Browser Error:
![Auswahl_184](https://user-images.githubusercontent.com/26381449/54460871-22a7b600-476b-11e9-9a75-c02ec23d858a.png)
No HA Error in the log.

## HA, Card, and Browser Versions:
Beta 0.90.0b2, latest CCH, FF and Chrome
