### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by jonostanck** [maykar/compact-custom-header#83]
## Describe the bug:
TypeError - Custom Header not loading.

## Config YAML:
```yaml
          - background_image: false
            type: 'custom:compact-custom-header'
            options: hide
            voice: hide

```
## HA and/or Browser Error:

Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.styleHeader (compact-custom-header.js?track=true:364)
    at HTMLElement.run (compact-custom-header.js?track=true:247)
    at HTMLElement.buildConfig (compact-custom-header.js?track=true:172)
    at HTMLElement.updated (compact-custom-header.js?track=true:75)
    at HTMLElement.performUpdate (app-1011b616.js:93)
    at HTMLElement._enqueueUpdate (app-1011b616.js:93)

Card not functional.

## HA, Card, and Browser Versions:

cch 1.0.1b7 (in 1.0.1b6 everything was ok)
Home Assistant 0.89.2
Chrome 73.0.3683.75
YAML

it's error for line `view.querySelector("hui-view").style.paddingTop = "55px";`
