### ISSUE TITLE
[Feature Request] Customize icon color of current tab.

### ISSUE THREAD

**Issue by maykar** [maykar/compact-custom-header#84]
**Is your feature request related to a problem? Please describe.**
Absolutely not!

**Describe the solution you'd like**
Customize the icon color of the view that you're currently on.

**Additional Context**
Ain't got none.

**Comment by maykar** [comment]
Added to the Dev branch

**Comment by Bastiencc** [comment]
OH ! Great work !!
I try all options, everything is ok except `tab_indicator_color`  : 
```
      - type: 'custom:compact-custom-header'
        main_config: true
        menu: overflow
        notifications: overflow
        voice: hide
        options: overflow
        clock_format: 24
        background_color: transparent # header background color
        all_buttons_color: black # color of all buttons unless set in button_color
        all_tabs_color: black # color of all tabs unless set in tab_color
        tab_color:
          0: rgb(214, 110, 19)
          1: rgb(12, 107, 30)
          2: rgb(92, 14, 165)
          3: rgb(92, 14, 165)
          4: rgb(6, 62, 160)
          5: rgb(6, 62, 160)
          6: rgb(216, 0, 43)
        tab_indicator_color: rgb(19, 172, 198) # indicator under current tab
        notify_indicator_color: black # the notifications indicator
        notify_text_color: black # number inside notifications indicator
        exceptions:
          - conditions:
              user_agent: Windows
            config:
              disable: true
          - conditions:
              user: Marion
            config:
              hide_tabs: 6
```
![2019-03-17 11 37 45](https://user-images.githubusercontent.com/37021892/54489145-846e3a00-48a9-11e9-9cbd-c4b68e63c56c.jpg)
