### ISSUE TITLE
Don't work after update on 0.9.01

### ISSUE THREAD

**Issue by Pirol62** [maykar/compact-custom-header#87]
## Describe the bug:

 Simply does nothing after having HASSIO update to  0.90.1

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->

resources:
  - type: module
    url: /local/custom-weather-card-chart.js
  - type: module
    url: >-
      /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
  - type: js
    url: /local/bignumber-card.js?v=1
  - type: module
    url: /local/custom-cards/tracker-card.js?track=true
title: Home
views:
  - badges:
      - group.familie
      - person.jorg
      - person.yvonne
      - variable.housewife_present
      - sensor.netatmo_garten_temperature
      - sensor.next_sunrise
      - sensor.next_sunset
    cards:
      - type: 'custom:compact-custom-header'
        all_tabs_color: '#EDEDED'
        clock_format: 24
        options: clock
        tab_indicator_color: '#FFFF00'
        voice: hide
      - entities:
          - entity: light.wohnzimmer
          - entity: input_select.livingroom_scene
          - entity: light.colorlampe_tv
          - entity: light.essen_oben
          - entity: light.stlmp_essen_unten
          - entity: light.fenster_oben
          - entity: light.stlmp_fenster_unten
          - entity: light.lightstrip_essen
          - entity: light.spot1
          - entity: light.spot2
          - entity: light.on_off_wand_wz
        show_header_toggle: false
        theme: material_dark_green
```
..... all other cards are similar

## HA and/or Browser Error:

No pressure data found for Garten
12:10 components/netatmo/sensor.py (ERROR) - message first occured at 11:53 and shows up 34 times
Condition is currently not available: wind_bearing
12:10 components/sensor/openweathermap.py (WARNING) - message first occured at 11:53 and shows up 34 times
Error doing job: Task exception was never retrieved
11:54 deps/lib/python3.7/site-packages/pyupdate/ha_custom/custom_components.py (ERROR)
Error doing job: Task exception was never retrieved
11:53 helpers/entity_platform.py (ERROR) - message first occured at 11:53 and shows up 5 times
You are using a custom component for alexa_media.media_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
11:53 loader.py (WARNING)
