### ISSUE TITLE
Home view ok, other views top items blocked by header

### ISSUE THREAD

**Issue by RoRoo1977** [maykar/compact-custom-header#88]
## Describe the bug:
After updating HASS to 0.90 this issue occurred. I've updated the compact-custom-header to the latest version, but the header still covers the top part of the pages.
Example: https://imgur.com/a/SnevxlB

## Config YAML:
```yaml
views:
  - icon: 'mdi:home'
    path: default_view
    title: Home
    cards:
      - type: 'custom:compact-custom-header'
        main_config: true
        disable: false
        header: true
        voice: hide
        options: clock
        clock_format: 24
        clock_date: true

```
## HA and/or Browser Error:
No error messages

## HA, Card, and Browser Versions:
Home Assistant: 0.90.1
custom-card-header: 1.0.2b2

https://imgur.com/a/SnevxlB

I love this custom header! I'd like to keep using it :)

**Comment by RoRoo1977** [comment]
Never mind.. 
Strangely enough my views had the  - type: custom:compact-custom-header 

After moving them to the cards: place-holder everything was ok.

**Comment by Spankythemusical** [comment]
RoRoo1977, can you please explain what you did to remedy this issue?  I'm having the exact same issue and cannot figure it out.  Thank you.

**Comment by Spankythemusical** [comment]
I thought I had it, but I was wrong.  Can you kindly explain what you did in order to restore the top parts of the items?

**Comment by maykar** [comment]
Make sure you have this card in every view.

**Comment by Spankythemusical** [comment]
@mykar, thank you.  I guess I misunderstood the cache section.  It's almost 100% now.  The only view I cannot add the card to is a view that I have using the `'custom:surveillance-card'`   Adding the card causes that view to be blank.  Here is my Lovelace entry:

```
  - badges: []
    cards:
      - cameras:
          - entity: camera.dcam
            motion_entity: binary_sensor.dcam
          - entity: camera.fcam
            motion_entity: binary_sensor.fcam
          - entity: camera.rcam
            motion_entity: binary_sensor.rcam
          - entity: camera.ncam
            motion_entity: binary_sensor.ncam
        thumb_interval: 15
        type: 'custom:surveillance-card'
        update_interval: 2
    icon: 'mdi:cctv'
    panel: true
    title: Surveillance
```
