### ISSUE TITLE
compact header not loading in 0.90.2

### ISSUE THREAD

**Issue by kloknibor** [maykar/compact-custom-header#89]
## Describe the bug:

I get the following error in my chrome console and the compact header does not load : 
'''TypeError: Cannot read property 'querySelector' of null
    at compact-custom-header.lib.js?v0.2.7:17 '''

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->
title: Thús
resources:
  - url: /local/card-tools.js
    type: js
  - url: /local/layout-card.js
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js
    type: module
  - url: /local/surveillance-card.js?v=0
    type: module
  - url: /local/tracker-card.js?track=true
    type: module
views:
    # View tab title.
  - title: update
    panel: false
    cards:
      - type: custom:tracker-card
  - title: home
#    panel: true
    cards:
#      - type: custom:layout-card
#      layout: vertical
#      cards:
      - type: entities
        title: Entities card sample
        show_header_toggle: false
        entities:
          - climate.woonkamer
          - climate.slaapkamer
          - climate.studeerkamer
          - climate.warm_water
      - type: entities
        title: Entities card sample
        show_header_toggle: false
        entities:
          - binary_sensor.0x00158d00028de7c1_contact
          - binary_sensor.0x00158d00028de79b_contact
          - binary_sensor.0x00158d0002375c95_water_leak
      - type: picture-glance
        entities: []
        camera_image: camera.dafang3
      - type: weather-forecast
        entity: weather.br_unknown_station
      - type: media-control
        entity: media_player.spotify
      - type: custom:compact-custom-header

```
## HA and/or Browser Error:

'''TypeError: Cannot read property 'querySelector' of null
    at compact-custom-header.lib.js?v0.2.7:17 '''

## HA, Card, and Browser Versions:

ha : 0.90.2
compact header : 1.0.2b1
