### ISSUE TITLE
Notification condition slow to react after notification dismiss.

### ISSUE THREAD

**Issue by maykar** [maykar/compact-custom-header#92]
## Describe the bug:
Notification condition doesn't immediately trigger change on dismissing of notification, only when another entity updates or on refresh.

## Config YAML:
```yaml
type: 'custom:compact-custom-header'
conditional_styles:
  - entity: notifications
    condition:
      state: false
    button:
      notifications:
        hide: true
```
## HA and/or Browser Error:
No error

## HA, Card, and Browser Versions:
HA: 0.90.2, Card: 1.0.2b5, Chrome 73.0.3683.86
