### ISSUE TITLE
Can't get configuration options UI to show

### ISSUE THREAD

**Issue by FlintRiver** [maykar/compact-custom-header#93]
## Describe the bug:
This may be a complete failure on my part, if so, i apologize for wasting your time.  I cant seem to activate the configuration UI for the compact header.  The compact header is working as configured in configuration.yaml but I cant access the configuration menu. 

## Config YAML:
```yaml
title: Buchanan Castle
resources:
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /local/mini-media-player-bundle.js?v=0.9.2
    type: module
views:
  - title: Overview
    icon: mdi:castle
    theme: BlueNight
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.downstairs
          - type: thermostat
            entity: climate.upstairs
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.home_to_work
                name: Home to Work
              - type: sensor
                entity: sensor.work_to_home
                name: Work to Home
          - type: horizontal-stack       
            cards:          
              - type: sensor
                entity: sensor.home_to_school
                name: Home to School
              - type: sensor
                entity: sensor.school_to_work
                name: School to Work
          - type: custom:compact-custom-header
            main_config: true
            menu: overflow
            options: clock
```
## HA and/or Browser Error:
The only warning I get that appeared after installing compact-custom-header is..
```
2019-04-02 13:34:50 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```
## HA, Card, and Browser Versions:

HA 0.90.2
Chrome Browser
Windows 10
YAML Mode
compact-custom-header   1.0.2b5

![](https://i.imgur.com/23kBaSp.png)

**Comment by maykar** [comment]
This is a limitation of how Home Assistant handles stacks when editing the UI. If you're not using panel mode, then don't put CCH in any stacks.

```yaml
views:
  - title: Overview
    icon: mdi:castle
    theme: BlueNight
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        options: clock
      - type: weather-forecast
        entity: weather.dark_sky
```

If you notice any spacing issues then place CCH as the last card in the view, but not indented to be in the stack.

```yaml
views:
  - title: Overview
    icon: mdi:castle
    theme: BlueNight
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.downstairs
          - type: thermostat
            entity: climate.upstairs
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.home_to_work
                name: Home to Work
              - type: sensor
                entity: sensor.work_to_home
                name: Work to Home
          - type: horizontal-stack       
            cards:          
              - type: sensor
                entity: sensor.home_to_school
                name: Home to School
              - type: sensor
                entity: sensor.school_to_work
                name: School to Work
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        options: clock
```
