### ISSUE TITLE
Conditionally hidden buttons still take up space.

### ISSUE THREAD

**Issue by maykar** [maykar/compact-custom-header#95]
## Describe the bug:
Hidden buttons still take up space in the header when hidden with conditional styles.

## Config YAML:
```yaml
type: 'custom:compact-custom-header'
conditional_styles:
  - entity: notifications
    condition:
      state: false
    button:
      notifications:
        hide: true
```
## HA and/or Browser Error:
No error

## HA, Card, and Browser Versions:

HA: 0.90.2, Card: 1.0.2b5, Chrome 73.0.3683.86
