### ISSUE TITLE
[Feature Request] Conditional styling - allow Or conditions

### ISSUE THREAD

**Issue by kloggy** [maykar/compact-custom-header#96]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It may be possible now but I have not found a way... I'd like to change the tab icon colour based on _either_ of two entities. It appears that currently ```conditional_styles``` are processed sequentially? It's no big deal but it would be nice to have.

**Additional Context**
For example, if either ```sensor.cycle1_running``` or ```sensor.cycle2_running``` is 'Running' then set the tab colour to green:
```
          - entity: sensor.cycle1_running
            condition:
              state: 'Running'
            tab:
              3:
                color: green
        
          - entity: sensor.cycle2_running
            condition:
              state: 'Running'
            tab:
              3:
                color: green
```

**Comment by maykar** [comment]
I might revisit this at some point, but this can be accomplished by making a template sensor or a template binary sensor, for now.

Adding the example below to your config will make a new binary sensor called "cycle_running" that will have a state of "on" if either of the sensors are "running" and "off" otherwise. You can then use this new sensor for your conditional styling.

```
binary_sensor:
  - platform: template
    sensors:
      cycle_running:
        value_template: >-
          {{ is_state('sensor.cycle1_running', 'Running')
             or is_state('sensor.cycle2_running', 'Running') }}
```
