### ISSUE TITLE
[Feature Request] Add "background-position:" to main & conditional config

### ISSUE THREAD

**Issue by maykar** [maykar/compact-custom-header#98]
**Is your feature request related to a problem? Please describe.**
Can't position background image

**Describe the solution you'd like**
Add "background-position:" to config

**Additional Context**

**Comment by DarrenRatcliffe** [comment]
Additional Context:

This could be achieved by adding the background-position code to config or it might be easier to allow for the parsing of additional elements other than URL to background-image as per the CSS spec?

**Comment by maykar** [comment]
I'll most likely just add the ability to use the more generic "background:" property so you could do things like:
`background: url(images/my-image.png) no-repeat center center / cover;`

**Comment by maykar** [comment]
In fact it might be best to eliminate both "background_image" & "background_color" in favor of just "background"

**Comment by maykar** [comment]
Added this to the dev branch if you wanted to give it a go. "background_image" & "background_color" have been replaced with "background" used like this.

In regular config:
```yaml
background: yellow
```
or:
```yaml
background: url(images/my-image.png) no-repeat center center / cover
```
In a conditional:
```yaml
  - entity: input_number.slider1
    condition:
      above: 10
    background: yellow
```

Reference:
[https://www.w3schools.com/cssref/css3_pr_background.asp](https://www.w3schools.com/cssref/css3_pr_background.asp)

**Comment by DarrenRatcliffe** [comment]
I will load, test and let you know tomorrow if that is OK?

**Comment by DarrenRatcliffe** [comment]
One thought on removing background_image and background_color, will it still be possible for someone to set both a color and an image together just using background? I won't need it but there may be scenarios where someone does?

**Comment by maykar** [comment]
You can do both or just one of either type with the background property

**Comment by DarrenRatcliffe** [comment]
OK just tried and it didn't work (the image didn't appear), here is the code:

```yaml
resources:
  - type: module
    url: /local/custom-cards/mini-media-player-bundle.js?v=1.0.1
  - type: module
    url: /local/custom-cards/mini-graph-card-bundle.js?v=0.3.0
  - type: module
    url: >-
      /local/custom-cards/compact-custom-header/compact-custom-header.js?v=1.0.2b8
title: Fernrock
views:
  - cards:
      - background: right url("/local/pics/pbi.png")
        main_config: true
        notifications: overflow
        type: 'custom:compact-custom-header'
        voice: overflow
```

**Comment by maykar** [comment]
I think it should be
```yaml
background: url("/local/pics/pbi.png") right
```

Edit: I'm wrong, either works

**Comment by maykar** [comment]
I think 
```yaml
background: url("/local/pics/pbi.png") right
```
would work fine too

**Comment by DarrenRatcliffe** [comment]
it doesn't seem to be working

Even if I only put:
`background: url("/local/pics/pbi.png")`

The image doesn't show yet it does with background_image

**Comment by maykar** [comment]
Sounds like a caching issue as background_image does not exist in the new code.

**Comment by DarrenRatcliffe** [comment]
Sorry I haven't retried background_image, it worked before I dropped the dev branch code in is what I meant

**Comment by DarrenRatcliffe** [comment]
I am seeing a strange effect if I use an incognito session in that when I log in to HA it loads with the standard theme with no header at all!

I have a standard browser still running and I am refreshing the cache so it has the right theme applied and this has a header but not showing the image

**Comment by maykar** [comment]
Have you increased the version number in resources and done a hard refresh (Ctrl + Shift + R)?
Are you using custom_updater?

**Comment by maykar** [comment]
Also, I apologize as `right url("/local/pics/pbi.png")` works just fine as well.

**Comment by maykar** [comment]
With this:
```yaml
background: right url('https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_960_720.jpg')
conditional_styles:
  - entity: input_number.slider1
    condition:
      above: 10
    background: left url('https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_960_720.jpg')
```
I get this:
![CCH_test_background](https://user-images.githubusercontent.com/25127328/55593508-25624f00-570a-11e9-80e3-ec4d3519f1eb.gif)

**Comment by DarrenRatcliffe** [comment]
OK, everything is refreshed (and rebooted), I have the dev code loaded this is my config:

```
resources:
  - type: module
    url: /local/custom-cards/mini-media-player-bundle.js?v=1.0.1
  - type: module
    url: /local/custom-cards/mini-graph-card-bundle.js?v=0.3.0
  - type: module
    url: >-
      /local/custom-cards/compact-custom-header/compact-custom-header.js?v=1.0.2b8
title: Fernrock
views:
  - cards:
      - type: 'custom:compact-custom-header'
        background: url('/local/pics/pbi.png')
        main_config: true
        notifications: overflow
        voice: overflow
```
Still doesn't work for me, do I need the background entry in every view / cards I have or is it OK to only have it in the primary one?

As you can see no image in the header in Chrome:

![image](https://user-images.githubusercontent.com/1911051/55610485-eddfbb00-577a-11e9-8358-29b978405536.png)

in Edge it says it can't load the custom-card!

![image](https://user-images.githubusercontent.com/1911051/55610554-110a6a80-577b-11e9-9007-e745cc0fd839.png)

I will carry on investigating
